// GENERATED by tool/gen_tokens.py from skill codicon.css — DO NOT EDIT BY HAND
// codicon 图标（fontFamily: 'codicon'，与 web 版同字体）
import 'package:flutter/widgets.dart';

class VsIcons {
  VsIcons._();

  /// codicon-add (U+0A60)
  static const IconData add = IconData(0xEA60, fontFamily: 'codicon');

  /// codicon-plus (U+0A60)
  static const IconData plus = IconData(0xEA60, fontFamily: 'codicon');

  /// codicon-gist-new (U+0A60)
  static const IconData gistNew = IconData(0xEA60, fontFamily: 'codicon');

  /// codicon-repo-create (U+0A60)
  static const IconData repoCreate = IconData(0xEA60, fontFamily: 'codicon');

  /// codicon-lightbulb (U+0A61)
  static const IconData lightbulb = IconData(0xEA61, fontFamily: 'codicon');

  /// codicon-light-bulb (U+0A61)
  static const IconData lightBulb = IconData(0xEA61, fontFamily: 'codicon');

  /// codicon-repo (U+0A62)
  static const IconData repo = IconData(0xEA62, fontFamily: 'codicon');

  /// codicon-repo-delete (U+0A62)
  static const IconData repoDelete = IconData(0xEA62, fontFamily: 'codicon');

  /// codicon-gist-fork (U+0A63)
  static const IconData gistFork = IconData(0xEA63, fontFamily: 'codicon');

  /// codicon-repo-forked (U+0A63)
  static const IconData repoForked = IconData(0xEA63, fontFamily: 'codicon');

  /// codicon-git-pull-request (U+0A64)
  static const IconData gitPullRequest = IconData(0xEA64, fontFamily: 'codicon');

  /// codicon-git-pull-request-abandoned (U+0A64)
  static const IconData gitPullRequestAbandoned = IconData(0xEA64, fontFamily: 'codicon');

  /// codicon-record-keys (U+0A65)
  static const IconData recordKeys = IconData(0xEA65, fontFamily: 'codicon');

  /// codicon-keyboard (U+0A65)
  static const IconData keyboard = IconData(0xEA65, fontFamily: 'codicon');

  /// codicon-tag (U+0A66)
  static const IconData tag = IconData(0xEA66, fontFamily: 'codicon');

  /// codicon-git-pull-request-label (U+0A66)
  static const IconData gitPullRequestLabel = IconData(0xEA66, fontFamily: 'codicon');

  /// codicon-tag-add (U+0A66)
  static const IconData tagAdd = IconData(0xEA66, fontFamily: 'codicon');

  /// codicon-tag-remove (U+0A66)
  static const IconData tagRemove = IconData(0xEA66, fontFamily: 'codicon');

  /// codicon-person (U+0A67)
  static const IconData person = IconData(0xEA67, fontFamily: 'codicon');

  /// codicon-person-follow (U+0A67)
  static const IconData personFollow = IconData(0xEA67, fontFamily: 'codicon');

  /// codicon-person-outline (U+0A67)
  static const IconData personOutline = IconData(0xEA67, fontFamily: 'codicon');

  /// codicon-person-filled (U+0A67)
  static const IconData personFilled = IconData(0xEA67, fontFamily: 'codicon');

  /// codicon-source-control (U+0A68)
  static const IconData sourceControl = IconData(0xEA68, fontFamily: 'codicon');

  /// codicon-mirror (U+0A69)
  static const IconData mirror = IconData(0xEA69, fontFamily: 'codicon');

  /// codicon-mirror-public (U+0A69)
  static const IconData mirrorPublic = IconData(0xEA69, fontFamily: 'codicon');

  /// codicon-star (U+0A6A)
  static const IconData star = IconData(0xEA6A, fontFamily: 'codicon');

  /// codicon-star-add (U+0A6A)
  static const IconData starAdd = IconData(0xEA6A, fontFamily: 'codicon');

  /// codicon-star-delete (U+0A6A)
  static const IconData starDelete = IconData(0xEA6A, fontFamily: 'codicon');

  /// codicon-star-empty (U+0A6A)
  static const IconData starEmpty = IconData(0xEA6A, fontFamily: 'codicon');

  /// codicon-comment (U+0A6B)
  static const IconData comment = IconData(0xEA6B, fontFamily: 'codicon');

  /// codicon-comment-add (U+0A6B)
  static const IconData commentAdd = IconData(0xEA6B, fontFamily: 'codicon');

  /// codicon-alert (U+0A6C)
  static const IconData alert = IconData(0xEA6C, fontFamily: 'codicon');

  /// codicon-warning (U+0A6C)
  static const IconData warning = IconData(0xEA6C, fontFamily: 'codicon');

  /// codicon-search (U+0A6D)
  static const IconData search = IconData(0xEA6D, fontFamily: 'codicon');

  /// codicon-search-save (U+0A6D)
  static const IconData searchSave = IconData(0xEA6D, fontFamily: 'codicon');

  /// codicon-log-out (U+0A6E)
  static const IconData logOut = IconData(0xEA6E, fontFamily: 'codicon');

  /// codicon-sign-out (U+0A6E)
  static const IconData signOut = IconData(0xEA6E, fontFamily: 'codicon');

  /// codicon-log-in (U+0A6F)
  static const IconData logIn = IconData(0xEA6F, fontFamily: 'codicon');

  /// codicon-sign-in (U+0A6F)
  static const IconData signIn = IconData(0xEA6F, fontFamily: 'codicon');

  /// codicon-eye (U+0A70)
  static const IconData eye = IconData(0xEA70, fontFamily: 'codicon');

  /// codicon-eye-unwatch (U+0A70)
  static const IconData eyeUnwatch = IconData(0xEA70, fontFamily: 'codicon');

  /// codicon-eye-watch (U+0A70)
  static const IconData eyeWatch = IconData(0xEA70, fontFamily: 'codicon');

  /// codicon-circle-filled (U+0A71)
  static const IconData circleFilled = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-primitive-dot (U+0A71)
  static const IconData primitiveDot = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-close-dirty (U+0A71)
  static const IconData closeDirty = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-debug-breakpoint (U+0A71)
  static const IconData debugBreakpoint = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-disabled (U+0A71)
  static const IconData debugBreakpointDisabled = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-debug-hint (U+0A71)
  static const IconData debugHint = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-terminal-decoration-success (U+0A71)
  static const IconData terminalDecorationSuccess = IconData(0xEA71, fontFamily: 'codicon');

  /// codicon-primitive-square (U+0A72)
  static const IconData primitiveSquare = IconData(0xEA72, fontFamily: 'codicon');

  /// codicon-edit (U+0A73)
  static const IconData edit = IconData(0xEA73, fontFamily: 'codicon');

  /// codicon-pencil (U+0A73)
  static const IconData pencil = IconData(0xEA73, fontFamily: 'codicon');

  /// codicon-info (U+0A74)
  static const IconData info = IconData(0xEA74, fontFamily: 'codicon');

  /// codicon-issue-opened (U+0A74)
  static const IconData issueOpened = IconData(0xEA74, fontFamily: 'codicon');

  /// codicon-gist-private (U+0A75)
  static const IconData gistPrivate = IconData(0xEA75, fontFamily: 'codicon');

  /// codicon-git-fork-private (U+0A75)
  static const IconData gitForkPrivate = IconData(0xEA75, fontFamily: 'codicon');

  /// codicon-lock (U+0A75)
  static const IconData lock = IconData(0xEA75, fontFamily: 'codicon');

  /// codicon-mirror-private (U+0A75)
  static const IconData mirrorPrivate = IconData(0xEA75, fontFamily: 'codicon');

  /// codicon-close (U+0A76)
  static const IconData close = IconData(0xEA76, fontFamily: 'codicon');

  /// codicon-remove-close (U+0A76)
  static const IconData removeClose = IconData(0xEA76, fontFamily: 'codicon');

  /// codicon-x (U+0A76)
  static const IconData x = IconData(0xEA76, fontFamily: 'codicon');

  /// codicon-repo-sync (U+0A77)
  static const IconData repoSync = IconData(0xEA77, fontFamily: 'codicon');

  /// codicon-sync (U+0A77)
  static const IconData sync = IconData(0xEA77, fontFamily: 'codicon');

  /// codicon-clone (U+0A78)
  static const IconData clone = IconData(0xEA78, fontFamily: 'codicon');

  /// codicon-desktop-download (U+0A78)
  static const IconData desktopDownload = IconData(0xEA78, fontFamily: 'codicon');

  /// codicon-beaker (U+0A79)
  static const IconData beaker = IconData(0xEA79, fontFamily: 'codicon');

  /// codicon-microscope (U+0A79)
  static const IconData microscope = IconData(0xEA79, fontFamily: 'codicon');

  /// codicon-vm (U+0A7A)
  static const IconData vm = IconData(0xEA7A, fontFamily: 'codicon');

  /// codicon-device-desktop (U+0A7A)
  static const IconData deviceDesktop = IconData(0xEA7A, fontFamily: 'codicon');

  /// codicon-file (U+0A7B)
  static const IconData file = IconData(0xEA7B, fontFamily: 'codicon');

  /// codicon-more (U+0A7C)
  static const IconData more = IconData(0xEA7C, fontFamily: 'codicon');

  /// codicon-ellipsis (U+0A7C)
  static const IconData ellipsis = IconData(0xEA7C, fontFamily: 'codicon');

  /// codicon-kebab-horizontal (U+0A7C)
  static const IconData kebabHorizontal = IconData(0xEA7C, fontFamily: 'codicon');

  /// codicon-mail-reply (U+0A7D)
  static const IconData mailReply = IconData(0xEA7D, fontFamily: 'codicon');

  /// codicon-reply (U+0A7D)
  static const IconData reply = IconData(0xEA7D, fontFamily: 'codicon');

  /// codicon-organization (U+0A7E)
  static const IconData organization = IconData(0xEA7E, fontFamily: 'codicon');

  /// codicon-organization-filled (U+0A7E)
  static const IconData organizationFilled = IconData(0xEA7E, fontFamily: 'codicon');

  /// codicon-organization-outline (U+0A7E)
  static const IconData organizationOutline = IconData(0xEA7E, fontFamily: 'codicon');

  /// codicon-new-file (U+0A7F)
  static const IconData newFile = IconData(0xEA7F, fontFamily: 'codicon');

  /// codicon-file-add (U+0A7F)
  static const IconData fileAdd = IconData(0xEA7F, fontFamily: 'codicon');

  /// codicon-new-folder (U+0A80)
  static const IconData newFolder = IconData(0xEA80, fontFamily: 'codicon');

  /// codicon-file-directory-create (U+0A80)
  static const IconData fileDirectoryCreate = IconData(0xEA80, fontFamily: 'codicon');

  /// codicon-trash (U+0A81)
  static const IconData trash = IconData(0xEA81, fontFamily: 'codicon');

  /// codicon-trashcan (U+0A81)
  static const IconData trashcan = IconData(0xEA81, fontFamily: 'codicon');

  /// codicon-history (U+0A82)
  static const IconData history = IconData(0xEA82, fontFamily: 'codicon');

  /// codicon-clock (U+0A82)
  static const IconData clock = IconData(0xEA82, fontFamily: 'codicon');

  /// codicon-folder (U+0A83)
  static const IconData folder = IconData(0xEA83, fontFamily: 'codicon');

  /// codicon-file-directory (U+0A83)
  static const IconData fileDirectory = IconData(0xEA83, fontFamily: 'codicon');

  /// codicon-symbol-folder (U+0A83)
  static const IconData symbolFolder = IconData(0xEA83, fontFamily: 'codicon');

  /// codicon-logo-github (U+0A84)
  static const IconData logoGithub = IconData(0xEA84, fontFamily: 'codicon');

  /// codicon-mark-github (U+0A84)
  static const IconData markGithub = IconData(0xEA84, fontFamily: 'codicon');

  /// codicon-github (U+0A84)
  static const IconData github = IconData(0xEA84, fontFamily: 'codicon');

  /// codicon-terminal (U+0A85)
  static const IconData terminal = IconData(0xEA85, fontFamily: 'codicon');

  /// codicon-console (U+0A85)
  static const IconData console = IconData(0xEA85, fontFamily: 'codicon');

  /// codicon-repl (U+0A85)
  static const IconData repl = IconData(0xEA85, fontFamily: 'codicon');

  /// codicon-zap (U+0A86)
  static const IconData zap = IconData(0xEA86, fontFamily: 'codicon');

  /// codicon-symbol-event (U+0A86)
  static const IconData symbolEvent = IconData(0xEA86, fontFamily: 'codicon');

  /// codicon-error (U+0A87)
  static const IconData error = IconData(0xEA87, fontFamily: 'codicon');

  /// codicon-stop (U+0A87)
  static const IconData stop = IconData(0xEA87, fontFamily: 'codicon');

  /// codicon-variable (U+0A88)
  static const IconData variable = IconData(0xEA88, fontFamily: 'codicon');

  /// codicon-symbol-variable (U+0A88)
  static const IconData symbolVariable = IconData(0xEA88, fontFamily: 'codicon');

  /// codicon-array (U+0A8A)
  static const IconData array = IconData(0xEA8A, fontFamily: 'codicon');

  /// codicon-symbol-array (U+0A8A)
  static const IconData symbolArray = IconData(0xEA8A, fontFamily: 'codicon');

  /// codicon-symbol-module (U+0A8B)
  static const IconData symbolModule = IconData(0xEA8B, fontFamily: 'codicon');

  /// codicon-symbol-package (U+0A8B)
  static const IconData symbolPackage = IconData(0xEA8B, fontFamily: 'codicon');

  /// codicon-symbol-namespace (U+0A8B)
  static const IconData symbolNamespace = IconData(0xEA8B, fontFamily: 'codicon');

  /// codicon-symbol-object (U+0A8B)
  static const IconData symbolObject = IconData(0xEA8B, fontFamily: 'codicon');

  /// codicon-symbol-method (U+0A8C)
  static const IconData symbolMethod = IconData(0xEA8C, fontFamily: 'codicon');

  /// codicon-symbol-function (U+0A8C)
  static const IconData symbolFunction = IconData(0xEA8C, fontFamily: 'codicon');

  /// codicon-symbol-constructor (U+0A8C)
  static const IconData symbolConstructor = IconData(0xEA8C, fontFamily: 'codicon');

  /// codicon-symbol-boolean (U+0A8F)
  static const IconData symbolBoolean = IconData(0xEA8F, fontFamily: 'codicon');

  /// codicon-symbol-null (U+0A8F)
  static const IconData symbolNull = IconData(0xEA8F, fontFamily: 'codicon');

  /// codicon-symbol-numeric (U+0A90)
  static const IconData symbolNumeric = IconData(0xEA90, fontFamily: 'codicon');

  /// codicon-symbol-number (U+0A90)
  static const IconData symbolNumber = IconData(0xEA90, fontFamily: 'codicon');

  /// codicon-symbol-structure (U+0A91)
  static const IconData symbolStructure = IconData(0xEA91, fontFamily: 'codicon');

  /// codicon-symbol-struct (U+0A91)
  static const IconData symbolStruct = IconData(0xEA91, fontFamily: 'codicon');

  /// codicon-symbol-parameter (U+0A92)
  static const IconData symbolParameter = IconData(0xEA92, fontFamily: 'codicon');

  /// codicon-symbol-type-parameter (U+0A92)
  static const IconData symbolTypeParameter = IconData(0xEA92, fontFamily: 'codicon');

  /// codicon-symbol-key (U+0A93)
  static const IconData symbolKey = IconData(0xEA93, fontFamily: 'codicon');

  /// codicon-symbol-text (U+0A93)
  static const IconData symbolText = IconData(0xEA93, fontFamily: 'codicon');

  /// codicon-symbol-reference (U+0A94)
  static const IconData symbolReference = IconData(0xEA94, fontFamily: 'codicon');

  /// codicon-go-to-file (U+0A94)
  static const IconData goToFile = IconData(0xEA94, fontFamily: 'codicon');

  /// codicon-symbol-enum (U+0A95)
  static const IconData symbolEnum = IconData(0xEA95, fontFamily: 'codicon');

  /// codicon-symbol-value (U+0A95)
  static const IconData symbolValue = IconData(0xEA95, fontFamily: 'codicon');

  /// codicon-symbol-ruler (U+0A96)
  static const IconData symbolRuler = IconData(0xEA96, fontFamily: 'codicon');

  /// codicon-symbol-unit (U+0A96)
  static const IconData symbolUnit = IconData(0xEA96, fontFamily: 'codicon');

  /// codicon-activate-breakpoints (U+0A97)
  static const IconData activateBreakpoints = IconData(0xEA97, fontFamily: 'codicon');

  /// codicon-archive (U+0A98)
  static const IconData archive = IconData(0xEA98, fontFamily: 'codicon');

  /// codicon-arrow-both (U+0A99)
  static const IconData arrowBoth = IconData(0xEA99, fontFamily: 'codicon');

  /// codicon-arrow-down (U+0A9A)
  static const IconData arrowDown = IconData(0xEA9A, fontFamily: 'codicon');

  /// codicon-arrow-left (U+0A9B)
  static const IconData arrowLeft = IconData(0xEA9B, fontFamily: 'codicon');

  /// codicon-arrow-right (U+0A9C)
  static const IconData arrowRight = IconData(0xEA9C, fontFamily: 'codicon');

  /// codicon-arrow-small-down (U+0A9D)
  static const IconData arrowSmallDown = IconData(0xEA9D, fontFamily: 'codicon');

  /// codicon-arrow-small-left (U+0A9E)
  static const IconData arrowSmallLeft = IconData(0xEA9E, fontFamily: 'codicon');

  /// codicon-arrow-small-right (U+0A9F)
  static const IconData arrowSmallRight = IconData(0xEA9F, fontFamily: 'codicon');

  /// codicon-arrow-small-up (U+0AA0)
  static const IconData arrowSmallUp = IconData(0xEAA0, fontFamily: 'codicon');

  /// codicon-arrow-up (U+0AA1)
  static const IconData arrowUp = IconData(0xEAA1, fontFamily: 'codicon');

  /// codicon-bell (U+0AA2)
  static const IconData bell = IconData(0xEAA2, fontFamily: 'codicon');

  /// codicon-bold (U+0AA3)
  static const IconData bold = IconData(0xEAA3, fontFamily: 'codicon');

  /// codicon-book (U+0AA4)
  static const IconData book = IconData(0xEAA4, fontFamily: 'codicon');

  /// codicon-bookmark (U+0AA5)
  static const IconData bookmark = IconData(0xEAA5, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-conditional-unverified (U+0AA6)
  static const IconData debugBreakpointConditionalUnverified = IconData(0xEAA6, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-conditional (U+0AA7)
  static const IconData debugBreakpointConditional = IconData(0xEAA7, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-conditional-disabled (U+0AA7)
  static const IconData debugBreakpointConditionalDisabled = IconData(0xEAA7, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-data-unverified (U+0AA8)
  static const IconData debugBreakpointDataUnverified = IconData(0xEAA8, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-data (U+0AA9)
  static const IconData debugBreakpointData = IconData(0xEAA9, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-data-disabled (U+0AA9)
  static const IconData debugBreakpointDataDisabled = IconData(0xEAA9, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-log-unverified (U+0AAA)
  static const IconData debugBreakpointLogUnverified = IconData(0xEAAA, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-log (U+0AAB)
  static const IconData debugBreakpointLog = IconData(0xEAAB, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-log-disabled (U+0AAB)
  static const IconData debugBreakpointLogDisabled = IconData(0xEAAB, fontFamily: 'codicon');

  /// codicon-briefcase (U+0AAC)
  static const IconData briefcase = IconData(0xEAAC, fontFamily: 'codicon');

  /// codicon-broadcast (U+0AAD)
  static const IconData broadcast = IconData(0xEAAD, fontFamily: 'codicon');

  /// codicon-browser (U+0AAE)
  static const IconData browser = IconData(0xEAAE, fontFamily: 'codicon');

  /// codicon-bug (U+0AAF)
  static const IconData bug = IconData(0xEAAF, fontFamily: 'codicon');

  /// codicon-calendar (U+0AB0)
  static const IconData calendar = IconData(0xEAB0, fontFamily: 'codicon');

  /// codicon-case-sensitive (U+0AB1)
  static const IconData caseSensitive = IconData(0xEAB1, fontFamily: 'codicon');

  /// codicon-check (U+0AB2)
  static const IconData check = IconData(0xEAB2, fontFamily: 'codicon');

  /// codicon-checklist (U+0AB3)
  static const IconData checklist = IconData(0xEAB3, fontFamily: 'codicon');

  /// codicon-chevron-down (U+0AB4)
  static const IconData chevronDown = IconData(0xEAB4, fontFamily: 'codicon');

  /// codicon-chevron-left (U+0AB5)
  static const IconData chevronLeft = IconData(0xEAB5, fontFamily: 'codicon');

  /// codicon-chevron-right (U+0AB6)
  static const IconData chevronRight = IconData(0xEAB6, fontFamily: 'codicon');

  /// codicon-chevron-up (U+0AB7)
  static const IconData chevronUp = IconData(0xEAB7, fontFamily: 'codicon');

  /// codicon-chrome-close (U+0AB8)
  static const IconData chromeClose = IconData(0xEAB8, fontFamily: 'codicon');

  /// codicon-chrome-maximize (U+0AB9)
  static const IconData chromeMaximize = IconData(0xEAB9, fontFamily: 'codicon');

  /// codicon-chrome-minimize (U+0ABA)
  static const IconData chromeMinimize = IconData(0xEABA, fontFamily: 'codicon');

  /// codicon-chrome-restore (U+0ABB)
  static const IconData chromeRestore = IconData(0xEABB, fontFamily: 'codicon');

  /// codicon-circle-outline (U+0ABC)
  static const IconData circleOutline = IconData(0xEABC, fontFamily: 'codicon');

  /// codicon-circle (U+0ABC)
  static const IconData circle = IconData(0xEABC, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-unverified (U+0ABC)
  static const IconData debugBreakpointUnverified = IconData(0xEABC, fontFamily: 'codicon');

  /// codicon-terminal-decoration-incomplete (U+0ABC)
  static const IconData terminalDecorationIncomplete = IconData(0xEABC, fontFamily: 'codicon');

  /// codicon-circle-slash (U+0ABD)
  static const IconData circleSlash = IconData(0xEABD, fontFamily: 'codicon');

  /// codicon-circuit-board (U+0ABE)
  static const IconData circuitBoard = IconData(0xEABE, fontFamily: 'codicon');

  /// codicon-clear-all (U+0ABF)
  static const IconData clearAll = IconData(0xEABF, fontFamily: 'codicon');

  /// codicon-clippy (U+0AC0)
  static const IconData clippy = IconData(0xEAC0, fontFamily: 'codicon');

  /// codicon-close-all (U+0AC1)
  static const IconData closeAll = IconData(0xEAC1, fontFamily: 'codicon');

  /// codicon-cloud-download (U+0AC2)
  static const IconData cloudDownload = IconData(0xEAC2, fontFamily: 'codicon');

  /// codicon-cloud-upload (U+0AC3)
  static const IconData cloudUpload = IconData(0xEAC3, fontFamily: 'codicon');

  /// codicon-code (U+0AC4)
  static const IconData code = IconData(0xEAC4, fontFamily: 'codicon');

  /// codicon-collapse-all (U+0AC5)
  static const IconData collapseAll = IconData(0xEAC5, fontFamily: 'codicon');

  /// codicon-color-mode (U+0AC6)
  static const IconData colorMode = IconData(0xEAC6, fontFamily: 'codicon');

  /// codicon-comment-discussion (U+0AC7)
  static const IconData commentDiscussion = IconData(0xEAC7, fontFamily: 'codicon');

  /// codicon-credit-card (U+0AC9)
  static const IconData creditCard = IconData(0xEAC9, fontFamily: 'codicon');

  /// codicon-dash (U+0ACC)
  static const IconData dash = IconData(0xEACC, fontFamily: 'codicon');

  /// codicon-dashboard (U+0ACD)
  static const IconData dashboard = IconData(0xEACD, fontFamily: 'codicon');

  /// codicon-database (U+0ACE)
  static const IconData database = IconData(0xEACE, fontFamily: 'codicon');

  /// codicon-debug-continue (U+0ACF)
  static const IconData debugContinue = IconData(0xEACF, fontFamily: 'codicon');

  /// codicon-debug-disconnect (U+0AD0)
  static const IconData debugDisconnect = IconData(0xEAD0, fontFamily: 'codicon');

  /// codicon-debug-pause (U+0AD1)
  static const IconData debugPause = IconData(0xEAD1, fontFamily: 'codicon');

  /// codicon-debug-restart (U+0AD2)
  static const IconData debugRestart = IconData(0xEAD2, fontFamily: 'codicon');

  /// codicon-debug-start (U+0AD3)
  static const IconData debugStart = IconData(0xEAD3, fontFamily: 'codicon');

  /// codicon-debug-step-into (U+0AD4)
  static const IconData debugStepInto = IconData(0xEAD4, fontFamily: 'codicon');

  /// codicon-debug-step-out (U+0AD5)
  static const IconData debugStepOut = IconData(0xEAD5, fontFamily: 'codicon');

  /// codicon-debug-step-over (U+0AD6)
  static const IconData debugStepOver = IconData(0xEAD6, fontFamily: 'codicon');

  /// codicon-debug-stop (U+0AD7)
  static const IconData debugStop = IconData(0xEAD7, fontFamily: 'codicon');

  /// codicon-debug (U+0AD8)
  static const IconData debug = IconData(0xEAD8, fontFamily: 'codicon');

  /// codicon-device-camera-video (U+0AD9)
  static const IconData deviceCameraVideo = IconData(0xEAD9, fontFamily: 'codicon');

  /// codicon-device-camera (U+0ADA)
  static const IconData deviceCamera = IconData(0xEADA, fontFamily: 'codicon');

  /// codicon-device-mobile (U+0ADB)
  static const IconData deviceMobile = IconData(0xEADB, fontFamily: 'codicon');

  /// codicon-diff-added (U+0ADC)
  static const IconData diffAdded = IconData(0xEADC, fontFamily: 'codicon');

  /// codicon-diff-ignored (U+0ADD)
  static const IconData diffIgnored = IconData(0xEADD, fontFamily: 'codicon');

  /// codicon-diff-modified (U+0ADE)
  static const IconData diffModified = IconData(0xEADE, fontFamily: 'codicon');

  /// codicon-diff-removed (U+0ADF)
  static const IconData diffRemoved = IconData(0xEADF, fontFamily: 'codicon');

  /// codicon-diff-renamed (U+0AE0)
  static const IconData diffRenamed = IconData(0xEAE0, fontFamily: 'codicon');

  /// codicon-diff (U+0AE1)
  static const IconData diff = IconData(0xEAE1, fontFamily: 'codicon');

  /// codicon-diff-sidebyside (U+0AE1)
  static const IconData diffSidebyside = IconData(0xEAE1, fontFamily: 'codicon');

  /// codicon-discard (U+0AE2)
  static const IconData discard = IconData(0xEAE2, fontFamily: 'codicon');

  /// codicon-editor-layout (U+0AE3)
  static const IconData editorLayout = IconData(0xEAE3, fontFamily: 'codicon');

  /// codicon-empty-window (U+0AE4)
  static const IconData emptyWindow = IconData(0xEAE4, fontFamily: 'codicon');

  /// codicon-exclude (U+0AE5)
  static const IconData exclude = IconData(0xEAE5, fontFamily: 'codicon');

  /// codicon-extensions (U+0AE6)
  static const IconData extensions = IconData(0xEAE6, fontFamily: 'codicon');

  /// codicon-eye-closed (U+0AE7)
  static const IconData eyeClosed = IconData(0xEAE7, fontFamily: 'codicon');

  /// codicon-file-binary (U+0AE8)
  static const IconData fileBinary = IconData(0xEAE8, fontFamily: 'codicon');

  /// codicon-file-code (U+0AE9)
  static const IconData fileCode = IconData(0xEAE9, fontFamily: 'codicon');

  /// codicon-file-media (U+0AEA)
  static const IconData fileMedia = IconData(0xEAEA, fontFamily: 'codicon');

  /// codicon-file-pdf (U+0AEB)
  static const IconData filePdf = IconData(0xEAEB, fontFamily: 'codicon');

  /// codicon-file-submodule (U+0AEC)
  static const IconData fileSubmodule = IconData(0xEAEC, fontFamily: 'codicon');

  /// codicon-file-symlink-directory (U+0AED)
  static const IconData fileSymlinkDirectory = IconData(0xEAED, fontFamily: 'codicon');

  /// codicon-file-symlink-file (U+0AEE)
  static const IconData fileSymlinkFile = IconData(0xEAEE, fontFamily: 'codicon');

  /// codicon-file-zip (U+0AEF)
  static const IconData fileZip = IconData(0xEAEF, fontFamily: 'codicon');

  /// codicon-files (U+0AF0)
  static const IconData files = IconData(0xEAF0, fontFamily: 'codicon');

  /// codicon-filter (U+0AF1)
  static const IconData filter = IconData(0xEAF1, fontFamily: 'codicon');

  /// codicon-flame (U+0AF2)
  static const IconData flame = IconData(0xEAF2, fontFamily: 'codicon');

  /// codicon-fold-down (U+0AF3)
  static const IconData foldDown = IconData(0xEAF3, fontFamily: 'codicon');

  /// codicon-fold-up (U+0AF4)
  static const IconData foldUp = IconData(0xEAF4, fontFamily: 'codicon');

  /// codicon-fold (U+0AF5)
  static const IconData fold = IconData(0xEAF5, fontFamily: 'codicon');

  /// codicon-folder-active (U+0AF6)
  static const IconData folderActive = IconData(0xEAF6, fontFamily: 'codicon');

  /// codicon-folder-opened (U+0AF7)
  static const IconData folderOpened = IconData(0xEAF7, fontFamily: 'codicon');

  /// codicon-gear (U+0AF8)
  static const IconData gear = IconData(0xEAF8, fontFamily: 'codicon');

  /// codicon-gift (U+0AF9)
  static const IconData gift = IconData(0xEAF9, fontFamily: 'codicon');

  /// codicon-gist-secret (U+0AFA)
  static const IconData gistSecret = IconData(0xEAFA, fontFamily: 'codicon');

  /// codicon-gist (U+0AFB)
  static const IconData gist = IconData(0xEAFB, fontFamily: 'codicon');

  /// codicon-git-commit (U+0AFC)
  static const IconData gitCommit = IconData(0xEAFC, fontFamily: 'codicon');

  /// codicon-git-compare (U+0AFD)
  static const IconData gitCompare = IconData(0xEAFD, fontFamily: 'codicon');

  /// codicon-compare-changes (U+0AFD)
  static const IconData compareChanges = IconData(0xEAFD, fontFamily: 'codicon');

  /// codicon-git-merge (U+0AFE)
  static const IconData gitMerge = IconData(0xEAFE, fontFamily: 'codicon');

  /// codicon-github-action (U+0AFF)
  static const IconData githubAction = IconData(0xEAFF, fontFamily: 'codicon');

  /// codicon-github-alt (U+0B00)
  static const IconData githubAlt = IconData(0xEB00, fontFamily: 'codicon');

  /// codicon-globe (U+0B01)
  static const IconData globe = IconData(0xEB01, fontFamily: 'codicon');

  /// codicon-grabber (U+0B02)
  static const IconData grabber = IconData(0xEB02, fontFamily: 'codicon');

  /// codicon-graph (U+0B03)
  static const IconData graph = IconData(0xEB03, fontFamily: 'codicon');

  /// codicon-gripper (U+0B04)
  static const IconData gripper = IconData(0xEB04, fontFamily: 'codicon');

  /// codicon-heart (U+0B05)
  static const IconData heart = IconData(0xEB05, fontFamily: 'codicon');

  /// codicon-home (U+0B06)
  static const IconData home = IconData(0xEB06, fontFamily: 'codicon');

  /// codicon-horizontal-rule (U+0B07)
  static const IconData horizontalRule = IconData(0xEB07, fontFamily: 'codicon');

  /// codicon-hubot (U+0B08)
  static const IconData hubot = IconData(0xEB08, fontFamily: 'codicon');

  /// codicon-inbox (U+0B09)
  static const IconData inbox = IconData(0xEB09, fontFamily: 'codicon');

  /// codicon-issue-reopened (U+0B0B)
  static const IconData issueReopened = IconData(0xEB0B, fontFamily: 'codicon');

  /// codicon-issues (U+0B0C)
  static const IconData issues = IconData(0xEB0C, fontFamily: 'codicon');

  /// codicon-italic (U+0B0D)
  static const IconData italic = IconData(0xEB0D, fontFamily: 'codicon');

  /// codicon-jersey (U+0B0E)
  static const IconData jersey = IconData(0xEB0E, fontFamily: 'codicon');

  /// codicon-json (U+0B0F)
  static const IconData json = IconData(0xEB0F, fontFamily: 'codicon');

  /// codicon-bracket (U+0B0F)
  static const IconData bracket = IconData(0xEB0F, fontFamily: 'codicon');

  /// codicon-kebab-vertical (U+0B10)
  static const IconData kebabVertical = IconData(0xEB10, fontFamily: 'codicon');

  /// codicon-key (U+0B11)
  static const IconData key = IconData(0xEB11, fontFamily: 'codicon');

  /// codicon-law (U+0B12)
  static const IconData law = IconData(0xEB12, fontFamily: 'codicon');

  /// codicon-lightbulb-autofix (U+0B13)
  static const IconData lightbulbAutofix = IconData(0xEB13, fontFamily: 'codicon');

  /// codicon-link-external (U+0B14)
  static const IconData linkExternal = IconData(0xEB14, fontFamily: 'codicon');

  /// codicon-link (U+0B15)
  static const IconData link = IconData(0xEB15, fontFamily: 'codicon');

  /// codicon-list-ordered (U+0B16)
  static const IconData listOrdered = IconData(0xEB16, fontFamily: 'codicon');

  /// codicon-list-unordered (U+0B17)
  static const IconData listUnordered = IconData(0xEB17, fontFamily: 'codicon');

  /// codicon-live-share (U+0B18)
  static const IconData liveShare = IconData(0xEB18, fontFamily: 'codicon');

  /// codicon-loading (U+0B19)
  static const IconData loading = IconData(0xEB19, fontFamily: 'codicon');

  /// codicon-location (U+0B1A)
  static const IconData location = IconData(0xEB1A, fontFamily: 'codicon');

  /// codicon-mail-read (U+0B1B)
  static const IconData mailRead = IconData(0xEB1B, fontFamily: 'codicon');

  /// codicon-mail (U+0B1C)
  static const IconData mail = IconData(0xEB1C, fontFamily: 'codicon');

  /// codicon-markdown (U+0B1D)
  static const IconData markdown = IconData(0xEB1D, fontFamily: 'codicon');

  /// codicon-megaphone (U+0B1E)
  static const IconData megaphone = IconData(0xEB1E, fontFamily: 'codicon');

  /// codicon-mention (U+0B1F)
  static const IconData mention = IconData(0xEB1F, fontFamily: 'codicon');

  /// codicon-milestone (U+0B20)
  static const IconData milestone = IconData(0xEB20, fontFamily: 'codicon');

  /// codicon-git-pull-request-milestone (U+0B20)
  static const IconData gitPullRequestMilestone = IconData(0xEB20, fontFamily: 'codicon');

  /// codicon-mortar-board (U+0B21)
  static const IconData mortarBoard = IconData(0xEB21, fontFamily: 'codicon');

  /// codicon-move (U+0B22)
  static const IconData move = IconData(0xEB22, fontFamily: 'codicon');

  /// codicon-multiple-windows (U+0B23)
  static const IconData multipleWindows = IconData(0xEB23, fontFamily: 'codicon');

  /// codicon-mute (U+0B24)
  static const IconData mute = IconData(0xEB24, fontFamily: 'codicon');

  /// codicon-no-newline (U+0B25)
  static const IconData noNewline = IconData(0xEB25, fontFamily: 'codicon');

  /// codicon-note (U+0B26)
  static const IconData note = IconData(0xEB26, fontFamily: 'codicon');

  /// codicon-octoface (U+0B27)
  static const IconData octoface = IconData(0xEB27, fontFamily: 'codicon');

  /// codicon-open-preview (U+0B28)
  static const IconData openPreview = IconData(0xEB28, fontFamily: 'codicon');

  /// codicon-package (U+0B29)
  static const IconData package = IconData(0xEB29, fontFamily: 'codicon');

  /// codicon-paintcan (U+0B2A)
  static const IconData paintcan = IconData(0xEB2A, fontFamily: 'codicon');

  /// codicon-pin (U+0B2B)
  static const IconData pin = IconData(0xEB2B, fontFamily: 'codicon');

  /// codicon-play (U+0B2C)
  static const IconData play = IconData(0xEB2C, fontFamily: 'codicon');

  /// codicon-run (U+0B2C)
  static const IconData run = IconData(0xEB2C, fontFamily: 'codicon');

  /// codicon-plug (U+0B2D)
  static const IconData plug = IconData(0xEB2D, fontFamily: 'codicon');

  /// codicon-preserve-case (U+0B2E)
  static const IconData preserveCase = IconData(0xEB2E, fontFamily: 'codicon');

  /// codicon-preview (U+0B2F)
  static const IconData preview = IconData(0xEB2F, fontFamily: 'codicon');

  /// codicon-project (U+0B30)
  static const IconData project = IconData(0xEB30, fontFamily: 'codicon');

  /// codicon-pulse (U+0B31)
  static const IconData pulse = IconData(0xEB31, fontFamily: 'codicon');

  /// codicon-question (U+0B32)
  static const IconData question = IconData(0xEB32, fontFamily: 'codicon');

  /// codicon-quote (U+0B33)
  static const IconData quote = IconData(0xEB33, fontFamily: 'codicon');

  /// codicon-radio-tower (U+0B34)
  static const IconData radioTower = IconData(0xEB34, fontFamily: 'codicon');

  /// codicon-reactions (U+0B35)
  static const IconData reactions = IconData(0xEB35, fontFamily: 'codicon');

  /// codicon-references (U+0B36)
  static const IconData references = IconData(0xEB36, fontFamily: 'codicon');

  /// codicon-refresh (U+0B37)
  static const IconData refresh = IconData(0xEB37, fontFamily: 'codicon');

  /// codicon-regex (U+0B38)
  static const IconData regex = IconData(0xEB38, fontFamily: 'codicon');

  /// codicon-remote-explorer (U+0B39)
  static const IconData remoteExplorer = IconData(0xEB39, fontFamily: 'codicon');

  /// codicon-remote (U+0B3A)
  static const IconData remote = IconData(0xEB3A, fontFamily: 'codicon');

  /// codicon-remove (U+0B3B)
  static const IconData remove = IconData(0xEB3B, fontFamily: 'codicon');

  /// codicon-replace-all (U+0B3C)
  static const IconData replaceAll = IconData(0xEB3C, fontFamily: 'codicon');

  /// codicon-replace (U+0B3D)
  static const IconData replace = IconData(0xEB3D, fontFamily: 'codicon');

  /// codicon-repo-clone (U+0B3E)
  static const IconData repoClone = IconData(0xEB3E, fontFamily: 'codicon');

  /// codicon-repo-force-push (U+0B3F)
  static const IconData repoForcePush = IconData(0xEB3F, fontFamily: 'codicon');

  /// codicon-repo-pull (U+0B40)
  static const IconData repoPull = IconData(0xEB40, fontFamily: 'codicon');

  /// codicon-repo-push (U+0B41)
  static const IconData repoPush = IconData(0xEB41, fontFamily: 'codicon');

  /// codicon-report (U+0B42)
  static const IconData report = IconData(0xEB42, fontFamily: 'codicon');

  /// codicon-request-changes (U+0B43)
  static const IconData requestChanges = IconData(0xEB43, fontFamily: 'codicon');

  /// codicon-rocket (U+0B44)
  static const IconData rocket = IconData(0xEB44, fontFamily: 'codicon');

  /// codicon-root-folder-opened (U+0B45)
  static const IconData rootFolderOpened = IconData(0xEB45, fontFamily: 'codicon');

  /// codicon-root-folder (U+0B46)
  static const IconData rootFolder = IconData(0xEB46, fontFamily: 'codicon');

  /// codicon-rss (U+0B47)
  static const IconData rss = IconData(0xEB47, fontFamily: 'codicon');

  /// codicon-ruby (U+0B48)
  static const IconData ruby = IconData(0xEB48, fontFamily: 'codicon');

  /// codicon-save-all (U+0B49)
  static const IconData saveAll = IconData(0xEB49, fontFamily: 'codicon');

  /// codicon-save-as (U+0B4A)
  static const IconData saveAs = IconData(0xEB4A, fontFamily: 'codicon');

  /// codicon-save (U+0B4B)
  static const IconData save = IconData(0xEB4B, fontFamily: 'codicon');

  /// codicon-screen-full (U+0B4C)
  static const IconData screenFull = IconData(0xEB4C, fontFamily: 'codicon');

  /// codicon-screen-normal (U+0B4D)
  static const IconData screenNormal = IconData(0xEB4D, fontFamily: 'codicon');

  /// codicon-search-stop (U+0B4E)
  static const IconData searchStop = IconData(0xEB4E, fontFamily: 'codicon');

  /// codicon-server (U+0B50)
  static const IconData server = IconData(0xEB50, fontFamily: 'codicon');

  /// codicon-settings-gear (U+0B51)
  static const IconData settingsGear = IconData(0xEB51, fontFamily: 'codicon');

  /// codicon-settings (U+0B52)
  static const IconData settings = IconData(0xEB52, fontFamily: 'codicon');

  /// codicon-shield (U+0B53)
  static const IconData shield = IconData(0xEB53, fontFamily: 'codicon');

  /// codicon-smiley (U+0B54)
  static const IconData smiley = IconData(0xEB54, fontFamily: 'codicon');

  /// codicon-sort-precedence (U+0B55)
  static const IconData sortPrecedence = IconData(0xEB55, fontFamily: 'codicon');

  /// codicon-split-horizontal (U+0B56)
  static const IconData splitHorizontal = IconData(0xEB56, fontFamily: 'codicon');

  /// codicon-split-vertical (U+0B57)
  static const IconData splitVertical = IconData(0xEB57, fontFamily: 'codicon');

  /// codicon-squirrel (U+0B58)
  static const IconData squirrel = IconData(0xEB58, fontFamily: 'codicon');

  /// codicon-star-full (U+0B59)
  static const IconData starFull = IconData(0xEB59, fontFamily: 'codicon');

  /// codicon-star-half (U+0B5A)
  static const IconData starHalf = IconData(0xEB5A, fontFamily: 'codicon');

  /// codicon-symbol-class (U+0B5B)
  static const IconData symbolClass = IconData(0xEB5B, fontFamily: 'codicon');

  /// codicon-symbol-color (U+0B5C)
  static const IconData symbolColor = IconData(0xEB5C, fontFamily: 'codicon');

  /// codicon-symbol-constant (U+0B5D)
  static const IconData symbolConstant = IconData(0xEB5D, fontFamily: 'codicon');

  /// codicon-symbol-enum-member (U+0B5E)
  static const IconData symbolEnumMember = IconData(0xEB5E, fontFamily: 'codicon');

  /// codicon-symbol-field (U+0B5F)
  static const IconData symbolField = IconData(0xEB5F, fontFamily: 'codicon');

  /// codicon-symbol-file (U+0B60)
  static const IconData symbolFile = IconData(0xEB60, fontFamily: 'codicon');

  /// codicon-symbol-interface (U+0B61)
  static const IconData symbolInterface = IconData(0xEB61, fontFamily: 'codicon');

  /// codicon-symbol-keyword (U+0B62)
  static const IconData symbolKeyword = IconData(0xEB62, fontFamily: 'codicon');

  /// codicon-symbol-misc (U+0B63)
  static const IconData symbolMisc = IconData(0xEB63, fontFamily: 'codicon');

  /// codicon-symbol-operator (U+0B64)
  static const IconData symbolOperator = IconData(0xEB64, fontFamily: 'codicon');

  /// codicon-symbol-property (U+0B65)
  static const IconData symbolProperty = IconData(0xEB65, fontFamily: 'codicon');

  /// codicon-wrench (U+0B65)
  static const IconData wrench = IconData(0xEB65, fontFamily: 'codicon');

  /// codicon-wrench-subaction (U+0B65)
  static const IconData wrenchSubaction = IconData(0xEB65, fontFamily: 'codicon');

  /// codicon-symbol-snippet (U+0B66)
  static const IconData symbolSnippet = IconData(0xEB66, fontFamily: 'codicon');

  /// codicon-tasklist (U+0B67)
  static const IconData tasklist = IconData(0xEB67, fontFamily: 'codicon');

  /// codicon-telescope (U+0B68)
  static const IconData telescope = IconData(0xEB68, fontFamily: 'codicon');

  /// codicon-text-size (U+0B69)
  static const IconData textSize = IconData(0xEB69, fontFamily: 'codicon');

  /// codicon-three-bars (U+0B6A)
  static const IconData threeBars = IconData(0xEB6A, fontFamily: 'codicon');

  /// codicon-thumbsdown (U+0B6B)
  static const IconData thumbsdown = IconData(0xEB6B, fontFamily: 'codicon');

  /// codicon-thumbsup (U+0B6C)
  static const IconData thumbsup = IconData(0xEB6C, fontFamily: 'codicon');

  /// codicon-tools (U+0B6D)
  static const IconData tools = IconData(0xEB6D, fontFamily: 'codicon');

  /// codicon-triangle-down (U+0B6E)
  static const IconData triangleDown = IconData(0xEB6E, fontFamily: 'codicon');

  /// codicon-triangle-left (U+0B6F)
  static const IconData triangleLeft = IconData(0xEB6F, fontFamily: 'codicon');

  /// codicon-triangle-right (U+0B70)
  static const IconData triangleRight = IconData(0xEB70, fontFamily: 'codicon');

  /// codicon-triangle-up (U+0B71)
  static const IconData triangleUp = IconData(0xEB71, fontFamily: 'codicon');

  /// codicon-twitter (U+0B72)
  static const IconData twitter = IconData(0xEB72, fontFamily: 'codicon');

  /// codicon-unfold (U+0B73)
  static const IconData unfold = IconData(0xEB73, fontFamily: 'codicon');

  /// codicon-unlock (U+0B74)
  static const IconData unlock = IconData(0xEB74, fontFamily: 'codicon');

  /// codicon-unmute (U+0B75)
  static const IconData unmute = IconData(0xEB75, fontFamily: 'codicon');

  /// codicon-unverified (U+0B76)
  static const IconData unverified = IconData(0xEB76, fontFamily: 'codicon');

  /// codicon-verified (U+0B77)
  static const IconData verified = IconData(0xEB77, fontFamily: 'codicon');

  /// codicon-versions (U+0B78)
  static const IconData versions = IconData(0xEB78, fontFamily: 'codicon');

  /// codicon-vm-active (U+0B79)
  static const IconData vmActive = IconData(0xEB79, fontFamily: 'codicon');

  /// codicon-vm-outline (U+0B7A)
  static const IconData vmOutline = IconData(0xEB7A, fontFamily: 'codicon');

  /// codicon-vm-running (U+0B7B)
  static const IconData vmRunning = IconData(0xEB7B, fontFamily: 'codicon');

  /// codicon-watch (U+0B7C)
  static const IconData watch = IconData(0xEB7C, fontFamily: 'codicon');

  /// codicon-whitespace (U+0B7D)
  static const IconData whitespace = IconData(0xEB7D, fontFamily: 'codicon');

  /// codicon-whole-word (U+0B7E)
  static const IconData wholeWord = IconData(0xEB7E, fontFamily: 'codicon');

  /// codicon-window (U+0B7F)
  static const IconData window = IconData(0xEB7F, fontFamily: 'codicon');

  /// codicon-word-wrap (U+0B80)
  static const IconData wordWrap = IconData(0xEB80, fontFamily: 'codicon');

  /// codicon-zoom-in (U+0B81)
  static const IconData zoomIn = IconData(0xEB81, fontFamily: 'codicon');

  /// codicon-zoom-out (U+0B82)
  static const IconData zoomOut = IconData(0xEB82, fontFamily: 'codicon');

  /// codicon-list-filter (U+0B83)
  static const IconData listFilter = IconData(0xEB83, fontFamily: 'codicon');

  /// codicon-list-flat (U+0B84)
  static const IconData listFlat = IconData(0xEB84, fontFamily: 'codicon');

  /// codicon-list-selection (U+0B85)
  static const IconData listSelection = IconData(0xEB85, fontFamily: 'codicon');

  /// codicon-selection (U+0B85)
  static const IconData selection = IconData(0xEB85, fontFamily: 'codicon');

  /// codicon-list-tree (U+0B86)
  static const IconData listTree = IconData(0xEB86, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-function-unverified (U+0B87)
  static const IconData debugBreakpointFunctionUnverified = IconData(0xEB87, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-function (U+0B88)
  static const IconData debugBreakpointFunction = IconData(0xEB88, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-function-disabled (U+0B88)
  static const IconData debugBreakpointFunctionDisabled = IconData(0xEB88, fontFamily: 'codicon');

  /// codicon-debug-stackframe-active (U+0B89)
  static const IconData debugStackframeActive = IconData(0xEB89, fontFamily: 'codicon');

  /// codicon-circle-small-filled (U+0B8A)
  static const IconData circleSmallFilled = IconData(0xEB8A, fontFamily: 'codicon');

  /// codicon-debug-stackframe-dot (U+0B8A)
  static const IconData debugStackframeDot = IconData(0xEB8A, fontFamily: 'codicon');

  /// codicon-terminal-decoration-mark (U+0B8A)
  static const IconData terminalDecorationMark = IconData(0xEB8A, fontFamily: 'codicon');

  /// codicon-debug-stackframe (U+0B8B)
  static const IconData debugStackframe = IconData(0xEB8B, fontFamily: 'codicon');

  /// codicon-debug-stackframe-focused (U+0B8B)
  static const IconData debugStackframeFocused = IconData(0xEB8B, fontFamily: 'codicon');

  /// codicon-debug-breakpoint-unsupported (U+0B8C)
  static const IconData debugBreakpointUnsupported = IconData(0xEB8C, fontFamily: 'codicon');

  /// codicon-symbol-string (U+0B8D)
  static const IconData symbolString = IconData(0xEB8D, fontFamily: 'codicon');

  /// codicon-debug-reverse-continue (U+0B8E)
  static const IconData debugReverseContinue = IconData(0xEB8E, fontFamily: 'codicon');

  /// codicon-debug-step-back (U+0B8F)
  static const IconData debugStepBack = IconData(0xEB8F, fontFamily: 'codicon');

  /// codicon-debug-restart-frame (U+0B90)
  static const IconData debugRestartFrame = IconData(0xEB90, fontFamily: 'codicon');

  /// codicon-debug-alt (U+0B91)
  static const IconData debugAlt = IconData(0xEB91, fontFamily: 'codicon');

  /// codicon-call-incoming (U+0B92)
  static const IconData callIncoming = IconData(0xEB92, fontFamily: 'codicon');

  /// codicon-call-outgoing (U+0B93)
  static const IconData callOutgoing = IconData(0xEB93, fontFamily: 'codicon');

  /// codicon-menu (U+0B94)
  static const IconData menu = IconData(0xEB94, fontFamily: 'codicon');

  /// codicon-expand-all (U+0B95)
  static const IconData expandAll = IconData(0xEB95, fontFamily: 'codicon');

  /// codicon-feedback (U+0B96)
  static const IconData feedback = IconData(0xEB96, fontFamily: 'codicon');

  /// codicon-git-pull-request-reviewer (U+0B96)
  static const IconData gitPullRequestReviewer = IconData(0xEB96, fontFamily: 'codicon');

  /// codicon-group-by-ref-type (U+0B97)
  static const IconData groupByRefType = IconData(0xEB97, fontFamily: 'codicon');

  /// codicon-ungroup-by-ref-type (U+0B98)
  static const IconData ungroupByRefType = IconData(0xEB98, fontFamily: 'codicon');

  /// codicon-account (U+0B99)
  static const IconData account = IconData(0xEB99, fontFamily: 'codicon');

  /// codicon-git-pull-request-assignee (U+0B99)
  static const IconData gitPullRequestAssignee = IconData(0xEB99, fontFamily: 'codicon');

  /// codicon-bell-dot (U+0B9A)
  static const IconData bellDot = IconData(0xEB9A, fontFamily: 'codicon');

  /// codicon-debug-console (U+0B9B)
  static const IconData debugConsole = IconData(0xEB9B, fontFamily: 'codicon');

  /// codicon-library (U+0B9C)
  static const IconData library = IconData(0xEB9C, fontFamily: 'codicon');

  /// codicon-output (U+0B9D)
  static const IconData output = IconData(0xEB9D, fontFamily: 'codicon');

  /// codicon-run-all (U+0B9E)
  static const IconData runAll = IconData(0xEB9E, fontFamily: 'codicon');

  /// codicon-sync-ignored (U+0B9F)
  static const IconData syncIgnored = IconData(0xEB9F, fontFamily: 'codicon');

  /// codicon-pinned (U+0BA0)
  static const IconData pinned = IconData(0xEBA0, fontFamily: 'codicon');

  /// codicon-github-inverted (U+0BA1)
  static const IconData githubInverted = IconData(0xEBA1, fontFamily: 'codicon');

  /// codicon-server-process (U+0BA2)
  static const IconData serverProcess = IconData(0xEBA2, fontFamily: 'codicon');

  /// codicon-server-environment (U+0BA3)
  static const IconData serverEnvironment = IconData(0xEBA3, fontFamily: 'codicon');

  /// codicon-pass (U+0BA4)
  static const IconData pass = IconData(0xEBA4, fontFamily: 'codicon');

  /// codicon-issue-closed (U+0BA4)
  static const IconData issueClosed = IconData(0xEBA4, fontFamily: 'codicon');

  /// codicon-stop-circle (U+0BA5)
  static const IconData stopCircle = IconData(0xEBA5, fontFamily: 'codicon');

  /// codicon-play-circle (U+0BA6)
  static const IconData playCircle = IconData(0xEBA6, fontFamily: 'codicon');

  /// codicon-record (U+0BA7)
  static const IconData record = IconData(0xEBA7, fontFamily: 'codicon');

  /// codicon-debug-alt-small (U+0BA8)
  static const IconData debugAltSmall = IconData(0xEBA8, fontFamily: 'codicon');

  /// codicon-vm-connect (U+0BA9)
  static const IconData vmConnect = IconData(0xEBA9, fontFamily: 'codicon');

  /// codicon-cloud (U+0BAA)
  static const IconData cloud = IconData(0xEBAA, fontFamily: 'codicon');

  /// codicon-merge (U+0BAB)
  static const IconData merge = IconData(0xEBAB, fontFamily: 'codicon');

  /// codicon-export (U+0BAC)
  static const IconData export = IconData(0xEBAC, fontFamily: 'codicon');

  /// codicon-graph-left (U+0BAD)
  static const IconData graphLeft = IconData(0xEBAD, fontFamily: 'codicon');

  /// codicon-magnet (U+0BAE)
  static const IconData magnet = IconData(0xEBAE, fontFamily: 'codicon');

  /// codicon-notebook (U+0BAF)
  static const IconData notebook = IconData(0xEBAF, fontFamily: 'codicon');

  /// codicon-redo (U+0BB0)
  static const IconData redo = IconData(0xEBB0, fontFamily: 'codicon');

  /// codicon-check-all (U+0BB1)
  static const IconData checkAll = IconData(0xEBB1, fontFamily: 'codicon');

  /// codicon-pinned-dirty (U+0BB2)
  static const IconData pinnedDirty = IconData(0xEBB2, fontFamily: 'codicon');

  /// codicon-pass-filled (U+0BB3)
  static const IconData passFilled = IconData(0xEBB3, fontFamily: 'codicon');

  /// codicon-circle-large-filled (U+0BB4)
  static const IconData circleLargeFilled = IconData(0xEBB4, fontFamily: 'codicon');

  /// codicon-circle-large (U+0BB5)
  static const IconData circleLarge = IconData(0xEBB5, fontFamily: 'codicon');

  /// codicon-circle-large-outline (U+0BB5)
  static const IconData circleLargeOutline = IconData(0xEBB5, fontFamily: 'codicon');

  /// codicon-combine (U+0BB6)
  static const IconData combine = IconData(0xEBB6, fontFamily: 'codicon');

  /// codicon-gather (U+0BB6)
  static const IconData gather = IconData(0xEBB6, fontFamily: 'codicon');

  /// codicon-table (U+0BB7)
  static const IconData table = IconData(0xEBB7, fontFamily: 'codicon');

  /// codicon-variable-group (U+0BB8)
  static const IconData variableGroup = IconData(0xEBB8, fontFamily: 'codicon');

  /// codicon-type-hierarchy (U+0BB9)
  static const IconData typeHierarchy = IconData(0xEBB9, fontFamily: 'codicon');

  /// codicon-type-hierarchy-sub (U+0BBA)
  static const IconData typeHierarchySub = IconData(0xEBBA, fontFamily: 'codicon');

  /// codicon-type-hierarchy-super (U+0BBB)
  static const IconData typeHierarchySuper = IconData(0xEBBB, fontFamily: 'codicon');

  /// codicon-git-pull-request-create (U+0BBC)
  static const IconData gitPullRequestCreate = IconData(0xEBBC, fontFamily: 'codicon');

  /// codicon-run-above (U+0BBD)
  static const IconData runAbove = IconData(0xEBBD, fontFamily: 'codicon');

  /// codicon-run-below (U+0BBE)
  static const IconData runBelow = IconData(0xEBBE, fontFamily: 'codicon');

  /// codicon-notebook-template (U+0BBF)
  static const IconData notebookTemplate = IconData(0xEBBF, fontFamily: 'codicon');

  /// codicon-debug-rerun (U+0BC0)
  static const IconData debugRerun = IconData(0xEBC0, fontFamily: 'codicon');

  /// codicon-workspace-trusted (U+0BC1)
  static const IconData workspaceTrusted = IconData(0xEBC1, fontFamily: 'codicon');

  /// codicon-workspace-untrusted (U+0BC2)
  static const IconData workspaceUntrusted = IconData(0xEBC2, fontFamily: 'codicon');

  /// codicon-workspace-unknown (U+0BC3)
  static const IconData workspaceUnknown = IconData(0xEBC3, fontFamily: 'codicon');

  /// codicon-terminal-cmd (U+0BC4)
  static const IconData terminalCmd = IconData(0xEBC4, fontFamily: 'codicon');

  /// codicon-terminal-debian (U+0BC5)
  static const IconData terminalDebian = IconData(0xEBC5, fontFamily: 'codicon');

  /// codicon-terminal-linux (U+0BC6)
  static const IconData terminalLinux = IconData(0xEBC6, fontFamily: 'codicon');

  /// codicon-terminal-powershell (U+0BC7)
  static const IconData terminalPowershell = IconData(0xEBC7, fontFamily: 'codicon');

  /// codicon-terminal-tmux (U+0BC8)
  static const IconData terminalTmux = IconData(0xEBC8, fontFamily: 'codicon');

  /// codicon-terminal-ubuntu (U+0BC9)
  static const IconData terminalUbuntu = IconData(0xEBC9, fontFamily: 'codicon');

  /// codicon-terminal-bash (U+0BCA)
  static const IconData terminalBash = IconData(0xEBCA, fontFamily: 'codicon');

  /// codicon-arrow-swap (U+0BCB)
  static const IconData arrowSwap = IconData(0xEBCB, fontFamily: 'codicon');

  /// codicon-copy (U+0BCC)
  static const IconData copy = IconData(0xEBCC, fontFamily: 'codicon');

  /// codicon-person-add (U+0BCD)
  static const IconData personAdd = IconData(0xEBCD, fontFamily: 'codicon');

  /// codicon-filter-filled (U+0BCE)
  static const IconData filterFilled = IconData(0xEBCE, fontFamily: 'codicon');

  /// codicon-wand (U+0BCF)
  static const IconData wand = IconData(0xEBCF, fontFamily: 'codicon');

  /// codicon-debug-line-by-line (U+0BD0)
  static const IconData debugLineByLine = IconData(0xEBD0, fontFamily: 'codicon');

  /// codicon-inspect (U+0BD1)
  static const IconData inspect = IconData(0xEBD1, fontFamily: 'codicon');

  /// codicon-layers (U+0BD2)
  static const IconData layers = IconData(0xEBD2, fontFamily: 'codicon');

  /// codicon-layers-dot (U+0BD3)
  static const IconData layersDot = IconData(0xEBD3, fontFamily: 'codicon');

  /// codicon-layers-active (U+0BD4)
  static const IconData layersActive = IconData(0xEBD4, fontFamily: 'codicon');

  /// codicon-compass (U+0BD5)
  static const IconData compass = IconData(0xEBD5, fontFamily: 'codicon');

  /// codicon-compass-dot (U+0BD6)
  static const IconData compassDot = IconData(0xEBD6, fontFamily: 'codicon');

  /// codicon-compass-active (U+0BD7)
  static const IconData compassActive = IconData(0xEBD7, fontFamily: 'codicon');

  /// codicon-azure (U+0BD8)
  static const IconData azure = IconData(0xEBD8, fontFamily: 'codicon');

  /// codicon-issue-draft (U+0BD9)
  static const IconData issueDraft = IconData(0xEBD9, fontFamily: 'codicon');

  /// codicon-git-pull-request-closed (U+0BDA)
  static const IconData gitPullRequestClosed = IconData(0xEBDA, fontFamily: 'codicon');

  /// codicon-git-pull-request-draft (U+0BDB)
  static const IconData gitPullRequestDraft = IconData(0xEBDB, fontFamily: 'codicon');

  /// codicon-debug-all (U+0BDC)
  static const IconData debugAll = IconData(0xEBDC, fontFamily: 'codicon');

  /// codicon-debug-coverage (U+0BDD)
  static const IconData debugCoverage = IconData(0xEBDD, fontFamily: 'codicon');

  /// codicon-run-errors (U+0BDE)
  static const IconData runErrors = IconData(0xEBDE, fontFamily: 'codicon');

  /// codicon-folder-library (U+0BDF)
  static const IconData folderLibrary = IconData(0xEBDF, fontFamily: 'codicon');

  /// codicon-debug-continue-small (U+0BE0)
  static const IconData debugContinueSmall = IconData(0xEBE0, fontFamily: 'codicon');

  /// codicon-beaker-stop (U+0BE1)
  static const IconData beakerStop = IconData(0xEBE1, fontFamily: 'codicon');

  /// codicon-graph-line (U+0BE2)
  static const IconData graphLine = IconData(0xEBE2, fontFamily: 'codicon');

  /// codicon-graph-scatter (U+0BE3)
  static const IconData graphScatter = IconData(0xEBE3, fontFamily: 'codicon');

  /// codicon-pie-chart (U+0BE4)
  static const IconData pieChart = IconData(0xEBE4, fontFamily: 'codicon');

  /// codicon-bracket-dot (U+0BE5)
  static const IconData bracketDot = IconData(0xEBE5, fontFamily: 'codicon');

  /// codicon-bracket-error (U+0BE6)
  static const IconData bracketError = IconData(0xEBE6, fontFamily: 'codicon');

  /// codicon-lock-small (U+0BE7)
  static const IconData lockSmall = IconData(0xEBE7, fontFamily: 'codicon');

  /// codicon-azure-devops (U+0BE8)
  static const IconData azureDevops = IconData(0xEBE8, fontFamily: 'codicon');

  /// codicon-verified-filled (U+0BE9)
  static const IconData verifiedFilled = IconData(0xEBE9, fontFamily: 'codicon');

  /// codicon-newline (U+0BEA)
  static const IconData newline = IconData(0xEBEA, fontFamily: 'codicon');

  /// codicon-layout (U+0BEB)
  static const IconData layout = IconData(0xEBEB, fontFamily: 'codicon');

  /// codicon-layout-activitybar-left (U+0BEC)
  static const IconData layoutActivitybarLeft = IconData(0xEBEC, fontFamily: 'codicon');

  /// codicon-layout-activitybar-right (U+0BED)
  static const IconData layoutActivitybarRight = IconData(0xEBED, fontFamily: 'codicon');

  /// codicon-layout-panel-left (U+0BEE)
  static const IconData layoutPanelLeft = IconData(0xEBEE, fontFamily: 'codicon');

  /// codicon-layout-panel-center (U+0BEF)
  static const IconData layoutPanelCenter = IconData(0xEBEF, fontFamily: 'codicon');

  /// codicon-layout-panel-justify (U+0BF0)
  static const IconData layoutPanelJustify = IconData(0xEBF0, fontFamily: 'codicon');

  /// codicon-layout-panel-right (U+0BF1)
  static const IconData layoutPanelRight = IconData(0xEBF1, fontFamily: 'codicon');

  /// codicon-layout-panel (U+0BF2)
  static const IconData layoutPanel = IconData(0xEBF2, fontFamily: 'codicon');

  /// codicon-layout-sidebar-left (U+0BF3)
  static const IconData layoutSidebarLeft = IconData(0xEBF3, fontFamily: 'codicon');

  /// codicon-layout-sidebar-right (U+0BF4)
  static const IconData layoutSidebarRight = IconData(0xEBF4, fontFamily: 'codicon');

  /// codicon-layout-statusbar (U+0BF5)
  static const IconData layoutStatusbar = IconData(0xEBF5, fontFamily: 'codicon');

  /// codicon-layout-menubar (U+0BF6)
  static const IconData layoutMenubar = IconData(0xEBF6, fontFamily: 'codicon');

  /// codicon-layout-centered (U+0BF7)
  static const IconData layoutCentered = IconData(0xEBF7, fontFamily: 'codicon');

  /// codicon-target (U+0BF8)
  static const IconData target = IconData(0xEBF8, fontFamily: 'codicon');

  /// codicon-indent (U+0BF9)
  static const IconData indent = IconData(0xEBF9, fontFamily: 'codicon');

  /// codicon-record-small (U+0BFA)
  static const IconData recordSmall = IconData(0xEBFA, fontFamily: 'codicon');

  /// codicon-error-small (U+0BFB)
  static const IconData errorSmall = IconData(0xEBFB, fontFamily: 'codicon');

  /// codicon-terminal-decoration-error (U+0BFB)
  static const IconData terminalDecorationError = IconData(0xEBFB, fontFamily: 'codicon');

  /// codicon-arrow-circle-down (U+0BFC)
  static const IconData arrowCircleDown = IconData(0xEBFC, fontFamily: 'codicon');

  /// codicon-arrow-circle-left (U+0BFD)
  static const IconData arrowCircleLeft = IconData(0xEBFD, fontFamily: 'codicon');

  /// codicon-arrow-circle-right (U+0BFE)
  static const IconData arrowCircleRight = IconData(0xEBFE, fontFamily: 'codicon');

  /// codicon-arrow-circle-up (U+0BFF)
  static const IconData arrowCircleUp = IconData(0xEBFF, fontFamily: 'codicon');

  /// codicon-layout-sidebar-right-off (U+0C00)
  static const IconData layoutSidebarRightOff = IconData(0xEC00, fontFamily: 'codicon');

  /// codicon-layout-panel-off (U+0C01)
  static const IconData layoutPanelOff = IconData(0xEC01, fontFamily: 'codicon');

  /// codicon-layout-sidebar-left-off (U+0C02)
  static const IconData layoutSidebarLeftOff = IconData(0xEC02, fontFamily: 'codicon');

  /// codicon-blank (U+0C03)
  static const IconData blank = IconData(0xEC03, fontFamily: 'codicon');

  /// codicon-heart-filled (U+0C04)
  static const IconData heartFilled = IconData(0xEC04, fontFamily: 'codicon');

  /// codicon-map (U+0C05)
  static const IconData map = IconData(0xEC05, fontFamily: 'codicon');

  /// codicon-map-horizontal (U+0C05)
  static const IconData mapHorizontal = IconData(0xEC05, fontFamily: 'codicon');

  /// codicon-fold-horizontal (U+0C05)
  static const IconData foldHorizontal = IconData(0xEC05, fontFamily: 'codicon');

  /// codicon-map-filled (U+0C06)
  static const IconData mapFilled = IconData(0xEC06, fontFamily: 'codicon');

  /// codicon-map-horizontal-filled (U+0C06)
  static const IconData mapHorizontalFilled = IconData(0xEC06, fontFamily: 'codicon');

  /// codicon-fold-horizontal-filled (U+0C06)
  static const IconData foldHorizontalFilled = IconData(0xEC06, fontFamily: 'codicon');

  /// codicon-circle-small (U+0C07)
  static const IconData circleSmall = IconData(0xEC07, fontFamily: 'codicon');

  /// codicon-bell-slash (U+0C08)
  static const IconData bellSlash = IconData(0xEC08, fontFamily: 'codicon');

  /// codicon-bell-slash-dot (U+0C09)
  static const IconData bellSlashDot = IconData(0xEC09, fontFamily: 'codicon');

  /// codicon-comment-unresolved (U+0C0A)
  static const IconData commentUnresolved = IconData(0xEC0A, fontFamily: 'codicon');

  /// codicon-git-pull-request-go-to-changes (U+0C0B)
  static const IconData gitPullRequestGoToChanges = IconData(0xEC0B, fontFamily: 'codicon');

  /// codicon-git-pull-request-new-changes (U+0C0C)
  static const IconData gitPullRequestNewChanges = IconData(0xEC0C, fontFamily: 'codicon');

  /// codicon-search-fuzzy (U+0C0D)
  static const IconData searchFuzzy = IconData(0xEC0D, fontFamily: 'codicon');

  /// codicon-comment-draft (U+0C0E)
  static const IconData commentDraft = IconData(0xEC0E, fontFamily: 'codicon');

  /// codicon-send (U+0C0F)
  static const IconData send = IconData(0xEC0F, fontFamily: 'codicon');

  /// codicon-sparkle (U+0C10)
  static const IconData sparkle = IconData(0xEC10, fontFamily: 'codicon');

  /// codicon-insert (U+0C11)
  static const IconData insert = IconData(0xEC11, fontFamily: 'codicon');

  /// codicon-mic (U+0C12)
  static const IconData mic = IconData(0xEC12, fontFamily: 'codicon');

  /// codicon-thumbsdown-filled (U+0C13)
  static const IconData thumbsdownFilled = IconData(0xEC13, fontFamily: 'codicon');

  /// codicon-thumbsup-filled (U+0C14)
  static const IconData thumbsupFilled = IconData(0xEC14, fontFamily: 'codicon');

  /// codicon-coffee (U+0C15)
  static const IconData coffee = IconData(0xEC15, fontFamily: 'codicon');

  /// codicon-snake (U+0C16)
  static const IconData snake = IconData(0xEC16, fontFamily: 'codicon');

  /// codicon-game (U+0C17)
  static const IconData game = IconData(0xEC17, fontFamily: 'codicon');

  /// codicon-vr (U+0C18)
  static const IconData vr = IconData(0xEC18, fontFamily: 'codicon');

  /// codicon-chip (U+0C19)
  static const IconData chip = IconData(0xEC19, fontFamily: 'codicon');

  /// codicon-piano (U+0C1A)
  static const IconData piano = IconData(0xEC1A, fontFamily: 'codicon');

  /// codicon-music (U+0C1B)
  static const IconData music = IconData(0xEC1B, fontFamily: 'codicon');

  /// codicon-mic-filled (U+0C1C)
  static const IconData micFilled = IconData(0xEC1C, fontFamily: 'codicon');

  /// codicon-repo-fetch (U+0C1D)
  static const IconData repoFetch = IconData(0xEC1D, fontFamily: 'codicon');

  /// codicon-copilot (U+0C1E)
  static const IconData copilot = IconData(0xEC1E, fontFamily: 'codicon');

  /// codicon-lightbulb-sparkle (U+0C1F)
  static const IconData lightbulbSparkle = IconData(0xEC1F, fontFamily: 'codicon');

  /// codicon-robot (U+0C20)
  static const IconData robot = IconData(0xEC20, fontFamily: 'codicon');

  /// codicon-sparkle-filled (U+0C21)
  static const IconData sparkleFilled = IconData(0xEC21, fontFamily: 'codicon');

  /// codicon-diff-single (U+0C22)
  static const IconData diffSingle = IconData(0xEC22, fontFamily: 'codicon');

  /// codicon-diff-multiple (U+0C23)
  static const IconData diffMultiple = IconData(0xEC23, fontFamily: 'codicon');

  /// codicon-surround-with (U+0C24)
  static const IconData surroundWith = IconData(0xEC24, fontFamily: 'codicon');

  /// codicon-share (U+0C25)
  static const IconData share = IconData(0xEC25, fontFamily: 'codicon');

  /// codicon-git-stash (U+0C26)
  static const IconData gitStash = IconData(0xEC26, fontFamily: 'codicon');

  /// codicon-git-stash-apply (U+0C27)
  static const IconData gitStashApply = IconData(0xEC27, fontFamily: 'codicon');

  /// codicon-git-stash-pop (U+0C28)
  static const IconData gitStashPop = IconData(0xEC28, fontFamily: 'codicon');

  /// codicon-vscode (U+0C29)
  static const IconData vscode = IconData(0xEC29, fontFamily: 'codicon');

  /// codicon-vscode-insiders (U+0C2A)
  static const IconData vscodeInsiders = IconData(0xEC2A, fontFamily: 'codicon');

  /// codicon-code-oss (U+0C2B)
  static const IconData codeOss = IconData(0xEC2B, fontFamily: 'codicon');

  /// codicon-run-coverage (U+0C2C)
  static const IconData runCoverage = IconData(0xEC2C, fontFamily: 'codicon');

  /// codicon-run-all-coverage (U+0C2D)
  static const IconData runAllCoverage = IconData(0xEC2D, fontFamily: 'codicon');

  /// codicon-coverage (U+0C2E)
  static const IconData coverage = IconData(0xEC2E, fontFamily: 'codicon');

  /// codicon-github-project (U+0C2F)
  static const IconData githubProject = IconData(0xEC2F, fontFamily: 'codicon');

  /// codicon-map-vertical (U+0C30)
  static const IconData mapVertical = IconData(0xEC30, fontFamily: 'codicon');

  /// codicon-fold-vertical (U+0C30)
  static const IconData foldVertical = IconData(0xEC30, fontFamily: 'codicon');

  /// codicon-map-vertical-filled (U+0C31)
  static const IconData mapVerticalFilled = IconData(0xEC31, fontFamily: 'codicon');

  /// codicon-fold-vertical-filled (U+0C31)
  static const IconData foldVerticalFilled = IconData(0xEC31, fontFamily: 'codicon');

  /// codicon-go-to-search (U+0C32)
  static const IconData goToSearch = IconData(0xEC32, fontFamily: 'codicon');

  /// codicon-percentage (U+0C33)
  static const IconData percentage = IconData(0xEC33, fontFamily: 'codicon');

  /// codicon-sort-percentage (U+0C33)
  static const IconData sortPercentage = IconData(0xEC33, fontFamily: 'codicon');

  /// codicon-attach (U+0C34)
  static const IconData attach = IconData(0xEC34, fontFamily: 'codicon');

  /// codicon-go-to-editing-session (U+0C35)
  static const IconData goToEditingSession = IconData(0xEC35, fontFamily: 'codicon');

  /// codicon-edit-session (U+0C36)
  static const IconData editSession = IconData(0xEC36, fontFamily: 'codicon');

  /// codicon-code-review (U+0C37)
  static const IconData codeReview = IconData(0xEC37, fontFamily: 'codicon');

  /// codicon-copilot-warning (U+0C38)
  static const IconData copilotWarning = IconData(0xEC38, fontFamily: 'codicon');

  /// codicon-python (U+0C39)
  static const IconData python = IconData(0xEC39, fontFamily: 'codicon');

  /// codicon-copilot-large (U+0C3A)
  static const IconData copilotLarge = IconData(0xEC3A, fontFamily: 'codicon');

  /// codicon-copilot-warning-large (U+0C3B)
  static const IconData copilotWarningLarge = IconData(0xEC3B, fontFamily: 'codicon');

  /// codicon-keyboard-tab (U+0C3C)
  static const IconData keyboardTab = IconData(0xEC3C, fontFamily: 'codicon');

  /// codicon-copilot-blocked (U+0C3D)
  static const IconData copilotBlocked = IconData(0xEC3D, fontFamily: 'codicon');

  /// codicon-copilot-not-connected (U+0C3E)
  static const IconData copilotNotConnected = IconData(0xEC3E, fontFamily: 'codicon');

  /// codicon-flag (U+0C3F)
  static const IconData flag = IconData(0xEC3F, fontFamily: 'codicon');

  /// codicon-lightbulb-empty (U+0C40)
  static const IconData lightbulbEmpty = IconData(0xEC40, fontFamily: 'codicon');

  /// codicon-symbol-method-arrow (U+0C41)
  static const IconData symbolMethodArrow = IconData(0xEC41, fontFamily: 'codicon');

  /// codicon-copilot-unavailable (U+0C42)
  static const IconData copilotUnavailable = IconData(0xEC42, fontFamily: 'codicon');

  /// codicon-repo-pinned (U+0C43)
  static const IconData repoPinned = IconData(0xEC43, fontFamily: 'codicon');

  /// codicon-keyboard-tab-above (U+0C44)
  static const IconData keyboardTabAbove = IconData(0xEC44, fontFamily: 'codicon');

  /// codicon-keyboard-tab-below (U+0C45)
  static const IconData keyboardTabBelow = IconData(0xEC45, fontFamily: 'codicon');

  /// codicon-git-pull-request-done (U+0C46)
  static const IconData gitPullRequestDone = IconData(0xEC46, fontFamily: 'codicon');

  /// codicon-mcp (U+0C47)
  static const IconData mcp = IconData(0xEC47, fontFamily: 'codicon');

  /// codicon-extensions-large (U+0C48)
  static const IconData extensionsLarge = IconData(0xEC48, fontFamily: 'codicon');

  /// codicon-layout-panel-dock (U+0C49)
  static const IconData layoutPanelDock = IconData(0xEC49, fontFamily: 'codicon');

  /// codicon-layout-sidebar-left-dock (U+0C4A)
  static const IconData layoutSidebarLeftDock = IconData(0xEC4A, fontFamily: 'codicon');

  /// codicon-layout-sidebar-right-dock (U+0C4B)
  static const IconData layoutSidebarRightDock = IconData(0xEC4B, fontFamily: 'codicon');

  /// codicon-copilot-in-progress (U+0C4C)
  static const IconData copilotInProgress = IconData(0xEC4C, fontFamily: 'codicon');

  /// codicon-copilot-error (U+0C4D)
  static const IconData copilotError = IconData(0xEC4D, fontFamily: 'codicon');

  /// codicon-copilot-success (U+0C4E)
  static const IconData copilotSuccess = IconData(0xEC4E, fontFamily: 'codicon');

  /// codicon-chat-sparkle (U+0C4F)
  static const IconData chatSparkle = IconData(0xEC4F, fontFamily: 'codicon');

  /// codicon-search-sparkle (U+0C50)
  static const IconData searchSparkle = IconData(0xEC50, fontFamily: 'codicon');

  /// codicon-edit-sparkle (U+0C51)
  static const IconData editSparkle = IconData(0xEC51, fontFamily: 'codicon');

  /// codicon-copilot-snooze (U+0C52)
  static const IconData copilotSnooze = IconData(0xEC52, fontFamily: 'codicon');

  /// codicon-send-to-remote-agent (U+0C53)
  static const IconData sendToRemoteAgent = IconData(0xEC53, fontFamily: 'codicon');

  /// codicon-comment-discussion-sparkle (U+0C54)
  static const IconData commentDiscussionSparkle = IconData(0xEC54, fontFamily: 'codicon');

  /// codicon-chat-sparkle-warning (U+0C55)
  static const IconData chatSparkleWarning = IconData(0xEC55, fontFamily: 'codicon');

  /// codicon-chat-sparkle-error (U+0C56)
  static const IconData chatSparkleError = IconData(0xEC56, fontFamily: 'codicon');

  /// codicon-collection (U+0C57)
  static const IconData collection = IconData(0xEC57, fontFamily: 'codicon');

  /// codicon-new-collection (U+0C58)
  static const IconData newCollection = IconData(0xEC58, fontFamily: 'codicon');

  /// codicon-thinking (U+0C59)
  static const IconData thinking = IconData(0xEC59, fontFamily: 'codicon');

  /// codicon-build (U+0C5A)
  static const IconData build = IconData(0xEC5A, fontFamily: 'codicon');

  /// codicon-comment-discussion-quote (U+0C5B)
  static const IconData commentDiscussionQuote = IconData(0xEC5B, fontFamily: 'codicon');

  /// codicon-cursor (U+0C5C)
  static const IconData cursor = IconData(0xEC5C, fontFamily: 'codicon');

  /// codicon-eraser (U+0C5D)
  static const IconData eraser = IconData(0xEC5D, fontFamily: 'codicon');

  /// codicon-file-text (U+0C5E)
  static const IconData fileText = IconData(0xEC5E, fontFamily: 'codicon');

  /// codicon-quotes (U+0C60)
  static const IconData quotes = IconData(0xEC60, fontFamily: 'codicon');

  /// codicon-rename (U+0C61)
  static const IconData rename = IconData(0xEC61, fontFamily: 'codicon');

  /// codicon-run-with-deps (U+0C62)
  static const IconData runWithDeps = IconData(0xEC62, fontFamily: 'codicon');

  /// codicon-debug-connected (U+0C63)
  static const IconData debugConnected = IconData(0xEC63, fontFamily: 'codicon');

  /// codicon-strikethrough (U+0C64)
  static const IconData strikethrough = IconData(0xEC64, fontFamily: 'codicon');

  /// codicon-open-in-product (U+0C65)
  static const IconData openInProduct = IconData(0xEC65, fontFamily: 'codicon');

  /// codicon-index-zero (U+0C66)
  static const IconData indexZero = IconData(0xEC66, fontFamily: 'codicon');

  /// codicon-agent (U+0C67)
  static const IconData agent = IconData(0xEC67, fontFamily: 'codicon');

  /// codicon-edit-code (U+0C68)
  static const IconData editCode = IconData(0xEC68, fontFamily: 'codicon');

  /// codicon-repo-selected (U+0C69)
  static const IconData repoSelected = IconData(0xEC69, fontFamily: 'codicon');

  /// codicon-skip (U+0C6A)
  static const IconData skip = IconData(0xEC6A, fontFamily: 'codicon');

  /// codicon-merge-into (U+0C6B)
  static const IconData mergeInto = IconData(0xEC6B, fontFamily: 'codicon');

  /// codicon-git-branch-changes (U+0C6C)
  static const IconData gitBranchChanges = IconData(0xEC6C, fontFamily: 'codicon');

  /// codicon-git-branch-staged-changes (U+0C6D)
  static const IconData gitBranchStagedChanges = IconData(0xEC6D, fontFamily: 'codicon');

  /// codicon-git-branch-conflicts (U+0C6E)
  static const IconData gitBranchConflicts = IconData(0xEC6E, fontFamily: 'codicon');

  /// codicon-git-branch (U+0C6F)
  static const IconData gitBranch = IconData(0xEC6F, fontFamily: 'codicon');

  /// codicon-git-branch-create (U+0C6F)
  static const IconData gitBranchCreate = IconData(0xEC6F, fontFamily: 'codicon');

  /// codicon-git-branch-delete (U+0C6F)
  static const IconData gitBranchDelete = IconData(0xEC6F, fontFamily: 'codicon');

  /// codicon-search-large (U+0C70)
  static const IconData searchLarge = IconData(0xEC70, fontFamily: 'codicon');

  /// codicon-terminal-git-bash (U+0C71)
  static const IconData terminalGitBash = IconData(0xEC71, fontFamily: 'codicon');

  /// codicon-window-active (U+0C72)
  static const IconData windowActive = IconData(0xEC72, fontFamily: 'codicon');

  /// codicon-forward (U+0C73)
  static const IconData forward = IconData(0xEC73, fontFamily: 'codicon');

  /// codicon-download (U+0C74)
  static const IconData download = IconData(0xEC74, fontFamily: 'codicon');

  /// codicon-clockface (U+0C75)
  static const IconData clockface = IconData(0xEC75, fontFamily: 'codicon');

  /// codicon-unarchive (U+0C76)
  static const IconData unarchive = IconData(0xEC76, fontFamily: 'codicon');

  /// codicon-session-in-progress (U+0C77)
  static const IconData sessionInProgress = IconData(0xEC77, fontFamily: 'codicon');

  /// codicon-collection-small (U+0C78)
  static const IconData collectionSmall = IconData(0xEC78, fontFamily: 'codicon');

  /// codicon-vm-small (U+0C79)
  static const IconData vmSmall = IconData(0xEC79, fontFamily: 'codicon');

  /// codicon-cloud-small (U+0C7A)
  static const IconData cloudSmall = IconData(0xEC7A, fontFamily: 'codicon');

  /// codicon-add-small (U+0C7B)
  static const IconData addSmall = IconData(0xEC7B, fontFamily: 'codicon');

  /// codicon-remove-small (U+0C7C)
  static const IconData removeSmall = IconData(0xEC7C, fontFamily: 'codicon');

  /// codicon-worktree-small (U+0C7D)
  static const IconData worktreeSmall = IconData(0xEC7D, fontFamily: 'codicon');

  /// codicon-worktree (U+0C7E)
  static const IconData worktree = IconData(0xEC7E, fontFamily: 'codicon');

  /// codicon-screen-cut (U+0C7F)
  static const IconData screenCut = IconData(0xEC7F, fontFamily: 'codicon');

  /// codicon-ask (U+0C80)
  static const IconData ask = IconData(0xEC80, fontFamily: 'codicon');

  /// codicon-openai (U+0C81)
  static const IconData openai = IconData(0xEC81, fontFamily: 'codicon');

  /// codicon-claude (U+0C82)
  static const IconData claude = IconData(0xEC82, fontFamily: 'codicon');

  /// codicon-open-in-window (U+0C83)
  static const IconData openInWindow = IconData(0xEC83, fontFamily: 'codicon');

  /// codicon-new-session (U+0C84)
  static const IconData newSession = IconData(0xEC84, fontFamily: 'codicon');

  /// codicon-terminal-secure (U+0C85)
  static const IconData terminalSecure = IconData(0xEC85, fontFamily: 'codicon');

  /// codicon-chat-import (U+0C86)
  static const IconData chatImport = IconData(0xEC86, fontFamily: 'codicon');

  /// codicon-chat-export (U+0C87)
  static const IconData chatExport = IconData(0xEC87, fontFamily: 'codicon');

  /// codicon-share-window (U+0C88)
  static const IconData shareWindow = IconData(0xEC88, fontFamily: 'codicon');

  /// codicon-circle-slash-compact (U+0C89)
  static const IconData circleSlashCompact = IconData(0xEC89, fontFamily: 'codicon');

  /// codicon-copilot-compact (U+0C8A)
  static const IconData copilotCompact = IconData(0xEC8A, fontFamily: 'codicon');

  /// codicon-folder-opened-compact (U+0C8B)
  static const IconData folderOpenedCompact = IconData(0xEC8B, fontFamily: 'codicon');

  /// codicon-folder-compact (U+0C8C)
  static const IconData folderCompact = IconData(0xEC8C, fontFamily: 'codicon');

  /// codicon-gear-compact (U+0C8D)
  static const IconData gearCompact = IconData(0xEC8D, fontFamily: 'codicon');

  /// codicon-git-branch-compact (U+0C8E)
  static const IconData gitBranchCompact = IconData(0xEC8E, fontFamily: 'codicon');

  /// codicon-library-compact (U+0C8F)
  static const IconData libraryCompact = IconData(0xEC8F, fontFamily: 'codicon');

  /// codicon-record-keys-compact (U+0C90)
  static const IconData recordKeysCompact = IconData(0xEC90, fontFamily: 'codicon');

  /// codicon-remote-compact (U+0C91)
  static const IconData remoteCompact = IconData(0xEC91, fontFamily: 'codicon');

  /// codicon-repo-forked-compact (U+0C92)
  static const IconData repoForkedCompact = IconData(0xEC92, fontFamily: 'codicon');

  /// codicon-repo-compact (U+0C93)
  static const IconData repoCompact = IconData(0xEC93, fontFamily: 'codicon');

  /// codicon-shield-compact (U+0C94)
  static const IconData shieldCompact = IconData(0xEC94, fontFamily: 'codicon');

  /// codicon-sparkle-compact (U+0C95)
  static const IconData sparkleCompact = IconData(0xEC95, fontFamily: 'codicon');

  /// codicon-symbol-color-compact (U+0C96)
  static const IconData symbolColorCompact = IconData(0xEC96, fontFamily: 'codicon');

  /// codicon-window-compact (U+0C97)
  static const IconData windowCompact = IconData(0xEC97, fontFamily: 'codicon');

  /// codicon-error-compact (U+0C98)
  static const IconData errorCompact = IconData(0xEC98, fontFamily: 'codicon');

  /// codicon-warning-compact (U+0C99)
  static const IconData warningCompact = IconData(0xEC99, fontFamily: 'codicon');

  /// codicon-pass-compact (U+0C9A)
  static const IconData passCompact = IconData(0xEC9A, fontFamily: 'codicon');

  /// codicon-important (U+0C9B)
  static const IconData important = IconData(0xEC9B, fontFamily: 'codicon');

  /// codicon-important-compact (U+0C9C)
  static const IconData importantCompact = IconData(0xEC9C, fontFamily: 'codicon');

  /// codicon-rocket-compact (U+0C9D)
  static const IconData rocketCompact = IconData(0xEC9D, fontFamily: 'codicon');

  /// codicon-unpin (U+0C9E)
  static const IconData unpin = IconData(0xEC9E, fontFamily: 'codicon');

  /// codicon-add-compact (U+0C9F)
  static const IconData addCompact = IconData(0xEC9F, fontFamily: 'codicon');

  /// codicon-attach-compact (U+0CA0)
  static const IconData attachCompact = IconData(0xECA0, fontFamily: 'codicon');

  /// codicon-beaker-compact (U+0CA1)
  static const IconData beakerCompact = IconData(0xECA1, fontFamily: 'codicon');

  /// codicon-check-compact (U+0CA2)
  static const IconData checkCompact = IconData(0xECA2, fontFamily: 'codicon');

  /// codicon-checklist-compact (U+0CA3)
  static const IconData checklistCompact = IconData(0xECA3, fontFamily: 'codicon');

  /// codicon-chevron-down-compact (U+0CA4)
  static const IconData chevronDownCompact = IconData(0xECA4, fontFamily: 'codicon');

  /// codicon-chevron-left-compact (U+0CA5)
  static const IconData chevronLeftCompact = IconData(0xECA5, fontFamily: 'codicon');

  /// codicon-chevron-right-compact (U+0CA6)
  static const IconData chevronRightCompact = IconData(0xECA6, fontFamily: 'codicon');

  /// codicon-chevron-up-compact (U+0CA7)
  static const IconData chevronUpCompact = IconData(0xECA7, fontFamily: 'codicon');

  /// codicon-circle-filled-compact (U+0CA8)
  static const IconData circleFilledCompact = IconData(0xECA8, fontFamily: 'codicon');

  /// codicon-circle-small-filled-compact (U+0CA9)
  static const IconData circleSmallFilledCompact = IconData(0xECA9, fontFamily: 'codicon');

  /// codicon-close-compact (U+0CAA)
  static const IconData closeCompact = IconData(0xECAA, fontFamily: 'codicon');

  /// codicon-collapse-all-compact (U+0CAB)
  static const IconData collapseAllCompact = IconData(0xECAB, fontFamily: 'codicon');

  /// codicon-comment-compact (U+0CAC)
  static const IconData commentCompact = IconData(0xECAC, fontFamily: 'codicon');

  /// codicon-comment-unresolved-compact (U+0CAD)
  static const IconData commentUnresolvedCompact = IconData(0xECAD, fontFamily: 'codicon');

  /// codicon-debug-connected-compact (U+0CAE)
  static const IconData debugConnectedCompact = IconData(0xECAE, fontFamily: 'codicon');

  /// codicon-debug-disconnect-compact (U+0CAF)
  static const IconData debugDisconnectCompact = IconData(0xECAF, fontFamily: 'codicon');

  /// codicon-edit-compact (U+0CB0)
  static const IconData editCompact = IconData(0xECB0, fontFamily: 'codicon');

  /// codicon-file-media-compact (U+0CB1)
  static const IconData fileMediaCompact = IconData(0xECB1, fontFamily: 'codicon');

  /// codicon-git-fetch (U+0CB2)
  static const IconData gitFetch = IconData(0xECB2, fontFamily: 'codicon');

  /// codicon-lightbulb-compact (U+0CB3)
  static const IconData lightbulbCompact = IconData(0xECB3, fontFamily: 'codicon');

  /// codicon-loading-compact (U+0CB4)
  static const IconData loadingCompact = IconData(0xECB4, fontFamily: 'codicon');

  /// codicon-pass-filled-compact (U+0CB5)
  static const IconData passFilledCompact = IconData(0xECB5, fontFamily: 'codicon');

  /// codicon-project-compact (U+0CB6)
  static const IconData projectCompact = IconData(0xECB6, fontFamily: 'codicon');

  /// codicon-refresh-compact (U+0CB7)
  static const IconData refreshCompact = IconData(0xECB7, fontFamily: 'codicon');

  /// codicon-search-compact (U+0CB8)
  static const IconData searchCompact = IconData(0xECB8, fontFamily: 'codicon');

  /// codicon-session-in-progress-compact (U+0CB9)
  static const IconData sessionInProgressCompact = IconData(0xECB9, fontFamily: 'codicon');

  /// codicon-sync-compact (U+0CBA)
  static const IconData syncCompact = IconData(0xECBA, fontFamily: 'codicon');

  /// codicon-terminal-compact (U+0CBB)
  static const IconData terminalCompact = IconData(0xECBB, fontFamily: 'codicon');

  /// codicon-vm-pending (U+0CBC)
  static const IconData vmPending = IconData(0xECBC, fontFamily: 'codicon');

  /// codicon-worktree-compact (U+0CBD)
  static const IconData worktreeCompact = IconData(0xECBD, fontFamily: 'codicon');

  /// codicon-developer-tools (U+0CBE)
  static const IconData developerTools = IconData(0xECBE, fontFamily: 'codicon');

  /// codicon-cloud-compact (U+0CBF)
  static const IconData cloudCompact = IconData(0xECBF, fontFamily: 'codicon');

  /// codicon-agent-compact (U+0CC0)
  static const IconData agentCompact = IconData(0xECC0, fontFamily: 'codicon');

  /// codicon-ask-compact (U+0CC1)
  static const IconData askCompact = IconData(0xECC1, fontFamily: 'codicon');

  /// codicon-settings-compact (U+0CC2)
  static const IconData settingsCompact = IconData(0xECC2, fontFamily: 'codicon');

  /// codicon-vm-compact (U+0CC3)
  static const IconData vmCompact = IconData(0xECC3, fontFamily: 'codicon');

  /// codicon-run-compact (U+0CC4)
  static const IconData runCompact = IconData(0xECC4, fontFamily: 'codicon');

  /// codicon-git-pull-request-comment (U+0CC5)
  static const IconData gitPullRequestComment = IconData(0xECC5, fontFamily: 'codicon');

  /// codicon-git-pull-request-error (U+0CC6)
  static const IconData gitPullRequestError = IconData(0xECC6, fontFamily: 'codicon');

  /// codicon-right-panel-hide (U+0CC7)
  static const IconData rightPanelHide = IconData(0xECC7, fontFamily: 'codicon');

  /// codicon-right-panel-show (U+0CC8)
  static const IconData rightPanelShow = IconData(0xECC8, fontFamily: 'codicon');

  /// codicon-vscode-insiders-outline (U+0CC9)
  static const IconData vscodeInsidersOutline = IconData(0xECC9, fontFamily: 'codicon');

  /// codicon-vscode-outline (U+0CCA)
  static const IconData vscodeOutline = IconData(0xECCA, fontFamily: 'codicon');

  /// codicon-voice-mode (U+0CCB)
  static const IconData voiceMode = IconData(0xECCB, fontFamily: 'codicon');

  /// codicon-voice-mode-compact (U+0CCC)
  static const IconData voiceModeCompact = IconData(0xECCC, fontFamily: 'codicon');

  /// codicon-mic-download (U+0CCD)
  static const IconData micDownload = IconData(0xECCD, fontFamily: 'codicon');

  /// codicon-mic-download-compact (U+0CCE)
  static const IconData micDownloadCompact = IconData(0xECCE, fontFamily: 'codicon');

  /// codicon-voice-mode-download (U+0CCF)
  static const IconData voiceModeDownload = IconData(0xECCF, fontFamily: 'codicon');

  /// codicon-voice-mode-download-compact (U+0CD0)
  static const IconData voiceModeDownloadCompact = IconData(0xECD0, fontFamily: 'codicon');

  /// codicon-google-gemini (U+0CD1)
  static const IconData googleGemini = IconData(0xECD1, fontFamily: 'codicon');

  /// codicon-kimi (U+0CD2)
  static const IconData kimi = IconData(0xECD2, fontFamily: 'codicon');

  /// codicon-microsoft (U+0CD3)
  static const IconData microsoft = IconData(0xECD3, fontFamily: 'codicon');

  /// codicon-fish1-happy (U+0CD4)
  static const IconData fish1Happy = IconData(0xECD4, fontFamily: 'codicon');

  /// codicon-fish1-neutral (U+0CD5)
  static const IconData fish1Neutral = IconData(0xECD5, fontFamily: 'codicon');

  /// codicon-fish1-sad (U+0CD6)
  static const IconData fish1Sad = IconData(0xECD6, fontFamily: 'codicon');

  /// codicon-fish1-very-sad (U+0CD7)
  static const IconData fish1VerySad = IconData(0xECD7, fontFamily: 'codicon');

  /// codicon-fish2-happy (U+0CD8)
  static const IconData fish2Happy = IconData(0xECD8, fontFamily: 'codicon');

  /// codicon-fish2-neutral (U+0CD9)
  static const IconData fish2Neutral = IconData(0xECD9, fontFamily: 'codicon');

  /// codicon-fish2-sad (U+0CDA)
  static const IconData fish2Sad = IconData(0xECDA, fontFamily: 'codicon');

  /// codicon-fish2-very-sad (U+0CDB)
  static const IconData fish2VerySad = IconData(0xECDB, fontFamily: 'codicon');

  /// codicon-fish3-happy (U+0CDC)
  static const IconData fish3Happy = IconData(0xECDC, fontFamily: 'codicon');

  /// codicon-fish3-neutral (U+0CDD)
  static const IconData fish3Neutral = IconData(0xECDD, fontFamily: 'codicon');

  /// codicon-fish3-sad (U+0CDE)
  static const IconData fish3Sad = IconData(0xECDE, fontFamily: 'codicon');

  /// codicon-fish3-very-sad (U+0CDF)
  static const IconData fish3VerySad = IconData(0xECDF, fontFamily: 'codicon');

  /// codicon-fish4-happy (U+0CE0)
  static const IconData fish4Happy = IconData(0xECE0, fontFamily: 'codicon');

  /// codicon-fish4-neutral (U+0CE1)
  static const IconData fish4Neutral = IconData(0xECE1, fontFamily: 'codicon');

  /// codicon-fish4-sad (U+0CE2)
  static const IconData fish4Sad = IconData(0xECE2, fontFamily: 'codicon');

  /// codicon-fish4-very-sad (U+0CE3)
  static const IconData fish4VerySad = IconData(0xECE3, fontFamily: 'codicon');

  /// codicon-person-voice (U+0CE4)
  static const IconData personVoice = IconData(0xECE4, fontFamily: 'codicon');

  /// codicon-person-voice-compact (U+0CE5)
  static const IconData personVoiceCompact = IconData(0xECE5, fontFamily: 'codicon');

  /// codicon-person-voice-filled (U+0CE6)
  static const IconData personVoiceFilled = IconData(0xECE6, fontFamily: 'codicon');

  /// codicon-person-voice-filled-compact (U+0CE7)
  static const IconData personVoiceFilledCompact = IconData(0xECE7, fontFamily: 'codicon');

  /// codicon-cloud-download-compact (U+0CE8)
  static const IconData cloudDownloadCompact = IconData(0xECE8, fontFamily: 'codicon');

  /// codicon-cloud-upload-compact (U+0CE9)
  static const IconData cloudUploadCompact = IconData(0xECE9, fontFamily: 'codicon');

  /// codicon-mic-compact (U+0CEA)
  static const IconData micCompact = IconData(0xECEA, fontFamily: 'codicon');

  /// codicon-arrow-up-compact (U+0CEB)
  static const IconData arrowUpCompact = IconData(0xECEB, fontFamily: 'codicon');

  /// codicon-xai (U+0CEC)
  static const IconData xai = IconData(0xECEC, fontFamily: 'codicon');

  /// codicon-arrow-circle-up-sparkle (U+0CED)
  static const IconData arrowCircleUpSparkle = IconData(0xECED, fontFamily: 'codicon');

}