// GENERATED by tool/gen_tokens.py from skill tokens.css — DO NOT EDIT BY HAND
// VS Code Modern UI token 体系（深色主题默认值）
import 'package:flutter/material.dart';

class VsToken {
  VsToken._();

  /// activityBarTop-activeBackground = 默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:470）
  static const String activityBarTopActivebackground = "默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:470）";

  /// bodyFontSize = 13px
  static const String bodyFontSize = "13px";

  /// bodyFontSize-small = 12px
  static const String bodyFontSizeSmall = "12px";

  /// bodyFontSize-xSmall = 11px
  static const String bodyFontSizeXsmall = "11px";

  /// codiconFontSize = 16px
  static const String codiconFontSize = "16px";

  /// codiconFontSize-compact = 12px
  static const String codiconFontSizeCompact = "12px";

  /// cornerRadius-circle = 9999px
  static const String cornerRadiusCircle = "9999px";

  /// cornerRadius-large = 8px
  static const String cornerRadiusLarge = "8px";

  /// cornerRadius-medium = 6px
  static const String cornerRadiusMedium = "6px";

  /// cornerRadius-small = 4px
  static const String cornerRadiusSmall = "4px";

  /// cornerRadius-xLarge = 12px
  static const String cornerRadiusXlarge = "12px";

  /// cornerRadius-xSmall = 2px
  static const String cornerRadiusXsmall = "2px";

  /// editorGroup-focusedEmptyBorder = 默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:212）
  static const String editorGroupFocusedemptyborder = "默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:212）";

  /// fontSize-body1 = 13px
  static const String fontSizeBody1 = "13px";

  /// fontSize-body2 = 11px
  static const String fontSizeBody2 = "11px";

  /// fontSize-heading1 = 26px
  static const String fontSizeHeading1 = "26px";

  /// fontSize-heading2 = 18px
  static const String fontSizeHeading2 = "18px";

  /// fontSize-heading3 = 13px
  static const String fontSizeHeading3 = "13px";

  /// fontSize-label1 = 12px
  static const String fontSizeLabel1 = "12px";

  /// fontSize-label2 = 11px
  static const String fontSizeLabel2 = "11px";

  /// fontSize-label3 = 10px
  static const String fontSizeLabel3 = "10px";

  /// fontWeight-regular = 400
  static const String fontWeightRegular = "400";

  /// fontWeight-semiBold = 600
  static const String fontWeightSemibold = "600";

  /// list-filterMatchBorder = 默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:119）
  static const String listFiltermatchborder = "默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:119）";

  /// list-hoverForeground = 默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:69）
  static const String listHoverforeground = "默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:69）";

  /// list-inactiveFocusBackground = 默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:57）
  static const String listInactivefocusbackground = "默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:57）";

  /// list-inactiveSelectionForeground = 默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:49）
  static const String listInactiveselectionforeground = "默认值为 null（主题未定义，CSS 用 fallback）（_color_listColors.ts:49）";

  /// menubar-selectionBorder = 默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:733）
  static const String menubarSelectionborder = "默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:733）";

  /// panelSectionHeader-border = 仅高对比主题定义（contrastBorder）（_wb_theme.ts:547）
  static const String panelSectionHeaderBorder = "仅高对比主题定义（contrastBorder）（_wb_theme.ts:547）";

  /// sash-activeBorder = 未注册（1.133.0 无默认值）
  static const String sashActiveborder = "未注册（1.133.0 无默认值）";

  /// spacing-size100 = 10px
  static const String spacingSize100 = "10px";

  /// spacing-size120 = 12px
  static const String spacingSize120 = "12px";

  /// spacing-size160 = 16px
  static const String spacingSize160 = "16px";

  /// spacing-size20 = 2px
  static const String spacingSize20 = "2px";

  /// spacing-size200 = 20px
  static const String spacingSize200 = "20px";

  /// spacing-size240 = 24px
  static const String spacingSize240 = "24px";

  /// spacing-size280 = 28px
  static const String spacingSize280 = "28px";

  /// spacing-size320 = 32px
  static const String spacingSize320 = "32px";

  /// spacing-size360 = 36px
  static const String spacingSize360 = "36px";

  /// spacing-size40 = 4px
  static const String spacingSize40 = "4px";

  /// spacing-size400 = 40px
  static const String spacingSize400 = "40px";

  /// spacing-size60 = 6px
  static const String spacingSize60 = "6px";

  /// spacing-size80 = 8px
  static const String spacingSize80 = "8px";

  /// spacing-sizeNone = 0px
  static const String spacingSizenone = "0px";

  /// strokeThickness = 1px
  static const String strokeThickness = "1px";

  /// tab-dirtyBorderTop = 未注册（1.133.0 无默认值）
  static const String tabDirtybordertop = "未注册（1.133.0 无默认值）";

  /// tab-hoverForeground = 默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:90）
  static const String tabHoverforeground = "默认值为 null（主题未定义，CSS 用 fallback）（_wb_theme.ts:90）";

  /// toolbar-hoverOutline = 默认值为 null（主题未定义，CSS 用 fallback）（_color_editorColors.ts:354）
  static const String toolbarHoveroutline = "默认值为 null（主题未定义，CSS 用 fallback）（_color_editorColors.ts:354）";

  /// activityBar-activeBorder
  static const Color activityBarActiveborder = Color(0xFF0078D4);

  /// activityBar-background
  static const Color activityBarBackground = Color(0xFF181818);

  /// activityBar-border
  static const Color activityBarBorder = Color(0xFF2B2B2B);

  /// activityBar-foreground
  static const Color activityBarForeground = Color(0xFFD7D7D7);

  /// activityBar-inactiveForeground
  static const Color activityBarInactiveforeground = Color(0xFF868686);

  /// activityBarBadge-background
  static const Color activityBarBadgeBackground = Color(0xFF0078D4);

  /// activityBarBadge-foreground
  static const Color activityBarBadgeForeground = Color(0xFFFFFFFF);

  /// activityBarTop-activeBorder
  static const Color activityBarTopActiveborder = Color(0xFFE7E7E7);

  /// badge-background
  static const Color badgeBackground = Color(0xFF616161);

  /// badge-foreground
  static const Color badgeForeground = Color(0xFFF8F8F8);

  /// breadcrumb-focusForeground
  static const Color breadcrumbFocusforeground = Color(0xFFD1D1D1);

  /// breadcrumb-foreground
  static const Color breadcrumbForeground = Color.fromARGB(204, 204, 204, 204);

  /// button-background
  static const Color buttonBackground = Color(0xFF0078D4);

  /// button-foreground
  static const Color buttonForeground = Color(0xFFFFFFFF);

  /// button-hoverBackground
  static const Color buttonHoverbackground = Color(0xFF026EC1);

  /// charts-blue
  static const Color chartsBlue = Color(0xFF59A4F9);

  /// charts-green
  static const Color chartsGreen = Color(0xFF89D185);

  /// charts-orange
  static const Color chartsOrange = Color(0xFFEA5C00);

  /// charts-red
  static const Color chartsRed = Color(0xFFF14C4C);

  /// charts-yellow
  static const Color chartsYellow = Color(0xFFCCA700);

  /// checkbox-background
  static const Color checkboxBackground = Color(0xFF313131);

  /// checkbox-border
  static const Color checkboxBorder = Color(0xFF3C3C3C);

  /// checkbox-selectBackground
  static const Color checkboxSelectbackground = Color(0xFF202020);

  /// checkbox-selectBorder
  static const Color checkboxSelectborder = Color(0xFFCCCCCC);

  /// commandCenter-activeBackground
  static const Color commandCenterActivebackground = Color.fromARGB(20, 255, 255, 255);

  /// commandCenter-activeBorder
  static const Color commandCenterActiveborder = Color.fromARGB(76, 204, 204, 204);

  /// commandCenter-activeForeground
  static const Color commandCenterActiveforeground = Color(0xFFCCCCCC);

  /// commandCenter-background
  static const Color commandCenterBackground = Color.fromARGB(13, 255, 255, 255);

  /// commandCenter-border
  static const Color commandCenterBorder = Color.fromARGB(51, 204, 204, 204);

  /// commandCenter-foreground
  static const Color commandCenterForeground = Color(0xFFCCCCCC);

  /// commandCenter-inactiveBorder
  static const Color commandCenterInactiveborder = Color.fromARGB(64, 157, 157, 157);

  /// descriptionForeground
  static const Color descriptionForeground = Color(0xFF9D9D9D);

  /// disabledForeground
  static const Color disabledForeground = Color(0xFFCCCCCC);

  /// dropdown-background
  static const Color dropdownBackground = Color(0xFF313131);

  /// dropdown-border
  static const Color dropdownBorder = Color(0xFF3C3C3C);

  /// dropdown-foreground
  static const Color dropdownForeground = Color(0xFFCCCCCC);

  /// editor-background
  static const Color editorBackground = Color(0xFF1F1F1F);

  /// editor-foreground
  static const Color editorForeground = Color(0xFFCCCCCC);

  /// editorGroup-border
  static const Color editorGroupBorder = Color(0xFFFFFFFF);

  /// editorGroupHeader-tabsBackground
  static const Color editorGroupHeaderTabsbackground = Color(0xFF181818);

  /// editorGroupHeader-tabsBorder
  static const Color editorGroupHeaderTabsborder = Color(0xFF2B2B2B);

  /// editorInfo-foreground
  static const Color editorInfoForeground = Color(0xFF59A4F9);

  /// editorLineNumber-activeForeground
  static const Color editorLineNumberActiveforeground = Color(0xFFCCCCCC);

  /// editorLineNumber-foreground
  static const Color editorLineNumberForeground = Color(0xFF6E7681);

  /// editorWarning-foreground
  static const Color editorWarningForeground = Color(0xFFCCA700);

  /// editorWidget-background
  static const Color editorWidgetBackground = Color(0xFF202020);

  /// errorForeground
  static const Color errorForeground = Color(0xFFF85149);

  /// focusBorder
  static const Color focusBorder = Color(0xFF0078D4);

  /// foreground
  static const Color foreground = Color(0xFFCCCCCC);

  /// icon-foreground
  static const Color iconForeground = Color(0xFFCCCCCC);

  /// input-background
  static const Color inputBackground = Color(0xFF313131);

  /// input-border
  static const Color inputBorder = Color(0xFF3C3C3C);

  /// input-foreground
  static const Color inputForeground = Color(0xFFCCCCCC);

  /// input-placeholderForeground
  static const Color inputPlaceholderforeground = Color(0xFF989898);

  /// inputOption-activeBackground
  static const Color inputOptionActivebackground = Color(0xFF2489DB);

  /// inputOption-activeBorder
  static const Color inputOptionActiveborder = Color(0xFF2488DB);

  /// list-activeSelectionForeground
  static const Color listActiveselectionforeground = Color(0xFFFFFFFF);

  /// list-dropBackground
  static const Color listDropbackground = Color(0xFF383B3D);

  /// list-filterMatchBackground
  static const Color listFiltermatchbackground = Color(0xFFEA5C00);

  /// list-focusHighlightForeground
  static const Color listFocushighlightforeground = Color(0xFF2AAAFF);

  /// list-inactiveSelectionBackground
  static const Color listInactiveselectionbackground = Color(0xFF37373D);

  /// menu-separatorBackground
  static const Color menuSeparatorbackground = Color(0xFF454545);

  /// menubar-selectionBackground
  static const Color menubarSelectionbackground = Color(0xFF5A5D5E);

  /// panel-background
  static const Color panelBackground = Color(0xFF181818);

  /// panel-border
  static const Color panelBorder = Color(0xFF2B2B2B);

  /// panelInput-border
  static const Color panelInputBorder = Color(0xFF2B2B2B);

  /// panelTitle-activeBorder
  static const Color panelTitleActiveborder = Color(0xFF0078D4);

  /// panelTitle-activeForeground
  static const Color panelTitleActiveforeground = Color(0xFFCCCCCC);

  /// panelTitle-inactiveForeground
  static const Color panelTitleInactiveforeground = Color(0xFF9D9D9D);

  /// profileBadge-background
  static const Color profileBadgeBackground = Color(0xFF4D4D4D);

  /// profileBadge-foreground
  static const Color profileBadgeForeground = Color(0xFFFFFFFF);

  /// progressBar-background
  static const Color progressBarBackground = Color(0xFF0078D4);

  /// sash-hoverBorder
  static const Color sashHoverborder = Color(0xFF0078D4);

  /// scrollbarSlider-activeBackground
  static const Color scrollbarSliderActivebackground = Color.fromARGB(102, 191, 191, 191);

  /// scrollbarSlider-background
  static const Color scrollbarSliderBackground = Color.fromARGB(102, 121, 121, 121);

  /// scrollbarSlider-hoverBackground
  static const Color scrollbarSliderHoverbackground = Color.fromARGB(178, 100, 100, 100);

  /// sideBar-background
  static const Color sideBarBackground = Color(0xFF181818);

  /// sideBar-border
  static const Color sideBarBorder = Color(0xFF2B2B2B);

  /// sideBar-foreground
  static const Color sideBarForeground = Color(0xFFCCCCCC);

  /// sideBarSectionHeader-background
  static const Color sideBarSectionHeaderBackground = Color(0xFF181818);

  /// sideBarSectionHeader-border
  static const Color sideBarSectionHeaderBorder = Color(0xFF2B2B2B);

  /// sideBarSectionHeader-foreground
  static const Color sideBarSectionHeaderForeground = Color(0xFFCCCCCC);

  /// sideBarTitle-background
  static const Color sideBarTitleBackground = Color(0xFF181818);

  /// sideBarTitle-foreground
  static const Color sideBarTitleForeground = Color(0xFFCCCCCC);

  /// statusBar-background
  static const Color statusBarBackground = Color(0xFF181818);

  /// statusBar-border
  static const Color statusBarBorder = Color(0xFF2B2B2B);

  /// statusBar-foreground
  static const Color statusBarForeground = Color(0xFFCCCCCC);

  /// statusBarItem-compactHoverBackground
  static const Color statusBarItemCompacthoverbackground = Color.fromARGB(31, 255, 255, 255);

  /// statusBarItem-errorBackground
  static const Color statusBarItemErrorbackground = Color(0xFF95312C);

  /// statusBarItem-errorForeground
  static const Color statusBarItemErrorforeground = Color(0xFFFFFFFF);

  /// statusBarItem-errorHoverBackground
  static const Color statusBarItemErrorhoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-errorHoverForeground
  static const Color statusBarItemErrorhoverforeground = Color(0xFFFFFFFF);

  /// statusBarItem-focusBorder
  static const Color statusBarItemFocusborder = Color(0xFF0078D4);

  /// statusBarItem-hoverBackground
  static const Color statusBarItemHoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-hoverForeground
  static const Color statusBarItemHoverforeground = Color(0xFFFFFFFF);

  /// statusBarItem-offlineBackground
  static const Color statusBarItemOfflinebackground = Color(0xFF6C1717);

  /// statusBarItem-offlineForeground
  static const Color statusBarItemOfflineforeground = Color(0xFFFFFFFF);

  /// statusBarItem-offlineHoverBackground
  static const Color statusBarItemOfflinehoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-offlineHoverForeground
  static const Color statusBarItemOfflinehoverforeground = Color(0xFFFFFFFF);

  /// statusBarItem-prominentBackground
  static const Color statusBarItemProminentbackground = Color(0xFF6E7681);

  /// statusBarItem-prominentForeground
  static const Color statusBarItemProminentforeground = Color(0xFFCCCCCC);

  /// statusBarItem-prominentHoverBackground
  static const Color statusBarItemProminenthoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-prominentHoverForeground
  static const Color statusBarItemProminenthoverforeground = Color(0xFFFFFFFF);

  /// statusBarItem-remoteBackground
  static const Color statusBarItemRemotebackground = Color(0xFF0078D4);

  /// statusBarItem-remoteForeground
  static const Color statusBarItemRemoteforeground = Color(0xFFFFFFFF);

  /// statusBarItem-remoteHoverBackground
  static const Color statusBarItemRemotehoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-remoteHoverForeground
  static const Color statusBarItemRemotehoverforeground = Color(0xFFFFFFFF);

  /// statusBarItem-warningBackground
  static const Color statusBarItemWarningbackground = Color(0xFF7A6400);

  /// statusBarItem-warningForeground
  static const Color statusBarItemWarningforeground = Color(0xFFFFFFFF);

  /// statusBarItem-warningHoverBackground
  static const Color statusBarItemWarninghoverbackground = Color(0xFFF1F1F1);

  /// statusBarItem-warningHoverForeground
  static const Color statusBarItemWarninghoverforeground = Color(0xFFFFFFFF);

  /// surface-background
  static const Color surfaceBackground = Color(0xFF181818);

  /// surface-border
  static const Color surfaceBorder = Color.fromARGB(26, 204, 204, 204);

  /// surface-foreground
  static const Color surfaceForeground = Color(0xFFCCCCCC);

  /// tab-activeBackground
  static const Color tabActivebackground = Color(0xFF1F1F1F);

  /// tab-activeBorderTop
  static const Color tabActivebordertop = Color(0xFF0078D4);

  /// tab-activeForeground
  static const Color tabActiveforeground = Color(0xFFFFFFFF);

  /// tab-border
  static const Color tabBorder = Color(0xFF2B2B2B);

  /// tab-dragAndDropBorder
  static const Color tabDraganddropborder = Color(0xFFFFFFFF);

  /// tab-hoverBackground
  static const Color tabHoverbackground = Color(0xFF1F1F1F);

  /// tab-inactiveBackground
  static const Color tabInactivebackground = Color(0xFF181818);

  /// tab-inactiveForeground
  static const Color tabInactiveforeground = Color(0xFF9D9D9D);

  /// tab-selectedBackground
  static const Color tabSelectedbackground = Color(0xFF37373D);

  /// tab-selectedBorderTop
  static const Color tabSelectedbordertop = Color(0xFF6CADDF);

  /// tab-selectedForeground
  static const Color tabSelectedforeground = Color(0xFFFFFFFF);

  /// tab-unfocusedActiveBorderTop
  static const Color tabUnfocusedactivebordertop = Color(0xFF2B2B2B);

  /// tab-unfocusedActiveForeground
  static const Color tabUnfocusedactiveforeground = Color.fromARGB(128, 255, 255, 255);

  /// tab-unfocusedHoverBackground
  static const Color tabUnfocusedhoverbackground = Color(0xFF1F1F1F);

  /// tab-unfocusedInactiveBackground
  static const Color tabUnfocusedinactivebackground = Color(0xFF181818);

  /// tab-unfocusedInactiveForeground
  static const Color tabUnfocusedinactiveforeground = Color.fromARGB(128, 157, 157, 157);

  /// terminal-ansiBlue
  static const Color terminalAnsiblue = Color(0xFF2472C8);

  /// terminal-ansiCyan
  static const Color terminalAnsicyan = Color(0xFF11A8CD);

  /// terminal-ansiGreen
  static const Color terminalAnsigreen = Color(0xFF0DBC79);

  /// terminal-ansiRed
  static const Color terminalAnsired = Color(0xFFCD3131);

  /// terminal-ansiYellow
  static const Color terminalAnsiyellow = Color(0xFFE5E510);

  /// terminal-foreground
  static const Color terminalForeground = Color(0xFFCCCCCC);

  /// textLink-foreground
  static const Color textLinkForeground = Color(0xFF4DAAFC);

  /// titleBar-activeBackground
  static const Color titleBarActivebackground = Color(0xFF181818);

  /// titleBar-activeForeground
  static const Color titleBarActiveforeground = Color(0xFFCCCCCC);

  /// titleBar-border
  static const Color titleBarBorder = Color(0xFF2B2B2B);

  /// titleBar-inactiveBackground
  static const Color titleBarInactivebackground = Color(0xFF1F1F1F);

  /// titleBar-inactiveForeground
  static const Color titleBarInactiveforeground = Color(0xFF9D9D9D);

  /// toolbar-activeBackground
  static const Color toolbarActivebackground = Color.fromARGB(80, 106, 109, 110);

  /// toolbar-hoverBackground
  static const Color toolbarHoverbackground = Color(0xFF5A5D5E);

  /// widget-border
  static const Color widgetBorder = Color(0xFF313131);

}