# -*- coding: utf-8 -*-
"""从 skill 提取的 VS Code Modern UI token/codicon 生成 Dart 常量文件
用法: python tool/gen_tokens.py
输出: lib/theme/vs_tokens.dart（颜色 token）、lib/theme/vs_icons.dart（codicon 图标）
"""
import os
import re
import sys

sys.stdout.reconfigure(encoding="utf-8")

ROOT = os.path.dirname(os.path.abspath(__file__))
SKILL = os.path.normpath(os.path.join(ROOT, "..", "..", "skill", "vscode-modern-ui", "resources", "assets", "css"))
OUT = os.path.normpath(os.path.join(ROOT, "..", "lib", "theme"))

# ---------- tokens.css（尺寸）+ colors.css（颜色，vs-dark 段） ----------
def parse_tokens():
    out = {}
    # tokens.css：尺寸（13px 等字符串值）
    txt = open(os.path.join(SKILL, "tokens", "tokens.css"), encoding="utf-8").read()
    for mm in re.finditer(r'--vscode-([A-Za-z0-9\-]+)\s*:\s*([^;]+);', txt):
        name, val = mm.group(1), mm.group(2).strip()
        if name not in out:
            out[name] = val
    # colors.css：所有 vs-dark 块合并（主块 + colorRegistry 默认值块）
    txt = open(os.path.join(SKILL, "tokens", "colors.css"), encoding="utf-8").read()
    for m in re.finditer(r'\.monaco-workbench\.vs-dark\s*{(.*?)}', txt, re.S):
        for mm in re.finditer(r'--vscode-([A-Za-z0-9\-]+)\s*:\s*([^;]+);', m.group(1)):
            name, val = mm.group(1), mm.group(2).strip()
            # 值可能跨行混入注释与下一个变量声明（主题未定义场景）——截断清洗
            for marker in ("*/", "--vscode-", "\n"):
                idx = val.find(marker)
                if idx >= 0:
                    val = val[:idx].strip()
                    break
            if not val:
                continue
            if name not in out:
                out[name] = val
    return out


def color_literal(val):
    val = val.strip()
    # #hex
    m = re.match(r'#([0-9a-fA-F]{6}|[0-9a-fA-F]{8})', val)
    if m:
        h = m.group(1)
        if len(h) == 6:
            return "Color(0xFF" + h.upper() + ")"
        return "Color(0x" + h.upper() + ")"  # 8位含 alpha
    # rgb() / rgba()
    m = re.match(r'rgba?\(([^)]+)\)', val)
    if m:
        parts = [p.strip() for p in m.group(1).split(",")]
        try:
            r, g, b = int(float(parts[0])), int(float(parts[1])), int(float(parts[2]))
            a = float(parts[3]) if len(parts) > 3 else 1.0
            return "Color.fromARGB(%d, %d, %d, %d)" % (round(a * 255), r, g, b)
        except Exception:
            return None
    # 带 alpha 的 #aarrggbb? 上面已处理
    return None


def dart_ident(name):
    # --vscode-editor-background -> editorBackground
    parts = name.split("-")
    return parts[0] + "".join(p.capitalize() for p in parts[1:])


def gen_tokens(tokens):
    lines = [
        "// GENERATED by tool/gen_tokens.py from skill tokens.css — DO NOT EDIT BY HAND",
        "// VS Code Modern UI token 体系（深色主题默认值）",
        "import 'package:flutter/material.dart';",
        "",
        "class VsToken {",
        "  VsToken._();",
        "",
    ]
    # 排序：非颜色（数字/尺寸）放前面，颜色随后
    color_items = []
    other_items = []
    for name in sorted(tokens.keys()):
        lit = color_literal(tokens[name])
        if lit:
            color_items.append((name, lit))
        else:
            other_items.append((name, tokens[name]))
    for name, val in other_items:
        lines.append("  /// %s = %s" % (name, val))
        lines.append("  static const String %s = %s;" % (dart_ident(name), json_str(val)))
        lines.append("")
    for name, lit in color_items:
        lines.append("  /// %s" % name)
        lines.append("  static const Color %s = %s;" % (dart_ident(name), lit))
        lines.append("")
    lines.append("}")
    return "\n".join(lines)


def json_str(s):
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


# ---------- codicon.css ----------
def gen_icons():
    txt = open(os.path.join(SKILL, "codicon", "codicon.css"), encoding="utf-8").read()
    lines = [
        "// GENERATED by tool/gen_tokens.py from skill codicon.css — DO NOT EDIT BY HAND",
        "// codicon 图标（fontFamily: 'codicon'，与 web 版同字体）",
        "import 'package:flutter/widgets.dart';",
        "",
        "class VsIcons {",
        "  VsIcons._();",
        "",
    ]
    for mm in re.finditer(r'\.codicon-([a-z0-9\-]+):before\s*{\s*content:\s*"\\e([0-9a-f]+)"', txt):
        name, cp = mm.group(1), int(mm.group(2), 16)
        ident = dart_ident(name)
        lines.append("  /// codicon-%s (U+%04X)" % (name, cp))
        lines.append("  static const IconData %s = IconData(0x%04X, fontFamily: 'codicon');" % (ident, cp))
        lines.append("")
    lines.append("}")
    return "\n".join(lines)


def main():
    tokens = parse_tokens()
    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "vs_tokens.dart"), "w", encoding="utf-8") as f:
        f.write(gen_tokens(tokens))
    with open(os.path.join(OUT, "vs_icons.dart"), "w", encoding="utf-8") as f:
        f.write(gen_icons())
    print("tokens: %d vars -> vs_tokens.dart" % len(tokens))


if __name__ == "__main__":
    main()
